### ISSUE TITLE
Agenda Items - Open to Requests

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#104]
Hi all, we're interested in taking your agenda items for the meeting at the end of next month. People have requested in the past that items come in at least 2 weeks in advance, so now is the time to start putting them in. Please let the chairs now if you have any questions. 

You can click [here](https://github.com/patcg/meetings/issues/new?assignees=AramZS%2C+seanturner&labels=agenda%2B&template=agenda-item-template.md&title=Agenda+Request+-++) to open a new Agenda proposal issue or open a new issue through the standard interface.

**Comment by AramZS** [comment]
Hi all, I know many people wanted the agenda to lock in two weeks in advance. The upcoming meeting is March 21 & 23, in timezone A: 0800 CEST / 0700 BST / 0600 UTC / 0200 EDT / 2300 PDT (previous day) / 1400 Singapore / 1600 AEST

Please submit any items you wish to discuss.

**Comment by eriktaubeneck** [comment]
For anyone looking at this issue, not that **the times above are incorrect**. The correct times are [1800 AEDT / 1500 Singapore / 0800 CET / 0700 GMT / 0700 UTC / 0300 EDT / 0000 PDT](https://everytimezone.com/?t=6418f380,1a4) (see [admin: #12](https://github.com/patcg/admin/issues/12).)

**Comment by csharrison** [comment]
@AramZS would you mind linking to the evertytimezone.com link that @eriktaubeneck posted for future meetings? That is very helpful especially as we are crossing standard/daylight time boundaries :)

**Comment by eriktaubeneck** [comment]
credit where credit is due, I stole the link from @seanturner's post
