### ISSUE TITLE
Agenda Request -  Individual Draft groups and meetings

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#107]
## Agenda+: Individual Drafts Meeting times and info

There are now a few different ad-hoc meetings coming out of the work being done in https://github.com/patcg-individual-drafts. In order to make sure CG participants are aware and able to participate if needed I would like to reserve some time for representatives of these group to either submit on this thread or state themselves the info on how to get involved. If the answer is just "comment on the repo", that's fine too, but I'd like to give the larger group a very brief update on what activity is in there. 

## Time

15m - potential to expand if groups believe they have interesting reports to bring to the main group.

**Comment by eriktaubeneck** [comment]
IPA will begin holding biweekly meetings starting on Tuesday March 21st / Wednesday March 22nd. (Times won't conflict with PATCG meeting.)  [Details on how to get involved in this issue.](https://github.com/patcg-individual-drafts/ipa/issues/47)

I'll happily report back progress in those meetings to the PATCG, and invite folks to get involved.

**Comment by alexmturner** [comment]
For [Private Aggregation](https://github.com/patcg-individual-drafts/private-aggregation-api), filing issues in our repo is probably the best way to engage. We've also held one meeting on better supporting reach measurement; future (ad hoc) meetings will be organized in [this issue](https://github.com/patcg-individual-drafts/private-aggregation-api/issues/19). You can also follow the [Shared Storage](https://groups.google.com/u/1/a/chromium.org/g/shared-storage-api-announcements) and [FLEDGE](https://groups.google.com/a/chromium.org/g/fledge-api-announce/) mailing lists for update announcements.

Would be happy to present this info/report progress and we'd certainly invite everyone to get involved and give feedback.

**Comment by leeronisrael** [comment]
Details on how to get involved in the Topics call available [here](https://github.com/patcg-individual-drafts/topics/issues/115). We typically hold calls on a monthly basis (although the specific day shifts as we try to avoid conflicts with the other calls).

**Comment by michaelkleber** [comment]
Noteworthy outcome: If you tell @seanturner about any upcoming meeting, he will happily make an entry for it on the PATCG's W3C calendar, to better garner the attention of potentially-interested PATCG participants.

**Comment by seanturner** [comment]
@leeronisrael I've got to add it to the W3C calendar. I will probably call the meeting something like "PATCG Individual Drafts: Topics (adhoc meeting)" or something like that. We'll also have one for IPA called something similar and whatever other ones come along. 

I can use the details you provided in the link above about the 5/8, 6/5, 7/3, ... calls.  I assume you are okay with it being open to all? I ask because the calendar asks:

    Show joining information to:
        o Everyone, a W3C account is not required
        o Holders of a W3C account
        o People invited to the event and holders of a W3C account with Member access (default)
        o People invited to the event

**Comment by leeronisrael** [comment]
Yes, we are ok with it being open to all. Thanks @seanturner!
