### ISSUE TITLE
Agenda Request -  Presenting EXPAT

### ISSUE THREAD

**Issue by rotemdar** [patcg/meetings#121]
## Agenda+: Presenting EXPAT - Extension-based Private Advertising Technology

This proposal was made by eyeo, and is an evolution of our previous [SPECTACLE](https://gitlab.com/eyeo/pat/spectacle) proposal from 2020. 

The paper proposes to assemble together in one browser extension (1) ad filtering technology, (2) comprehensive consumer-facing privacy protection tools, and (3) a client-based privacy-preserving ad targeting engine, with UI that provides users with transparency and control.

The evolution from the previous proposal is in the inclusion of an API proposal, access management, and more security considerations to solve expected scenarios taken into account. Additionally, in order to enable online users to enforce their ads-related privacy choices, we propose to integrate this technology as part of an ad-filtering software

## Time

1 hour in total for presentation and Q&A.

### Links

[the EXPAT proposal](https://docs.google.com/document/d/1z-gltfuatQrjY3_ikiYwY4qx2XgLAdhPUFJbTMDUmkM/edit?usp=sharing)

**Comment by seanturner** [comment]
It is potentially just me, but I can't seem to access the gDoc. Can you upload the proposal/presentation to the London Repo:
https://github.com/patcg/meetings/tree/main/2023/06/14-london
Thanks!

**Comment by alexdaicu** [comment]
Thanks for raising this @seanturner. I checked the permissions on the document and they seemed to be fine, but for easier access, I also created a github repo and uploaded the proposal there.
Here is the link: https://github.com/alexdaicu/expat
