### ISSUE TITLE
Agenda Request - Methods for measuring privacy risk

### ISSUE THREAD

**Issue by grahammudd** [patcg/meetings#129]
## Agenda+: What do you want to discuss?

Across the existing and proposed privacy APIs, we see a wide range of anonymization techniques employed (k-anonymity, differential privacy, limiting entropy). Even within a single technique such as differential privacy, there isn’t a standardized implementation. As an example, the privacy unit differs between ARA and IPA. As this group has discussed, solutions that are able to maximize both privacy and utility will likely require a mix of several techniques.

Given that, we propose organizing a sub-group focused on methods for measuring privacy risk (or privacy creation). As an example [this recent paper](https://arxiv.org/abs/2304.07210) from the google sandbox team looks to measure the risk of re-identification in the topics API. The thinking is, if we can standardize on a framework for measuring privacy across techniques, we will accelerate the industry’s understanding and ultimate acceptance of these tools.

Goals:  1) Align on whether a sub-group effort would be productive, 2) align on goals for project 3) call for participants 

Facilitators:  @tgreasby & @grahammudd

## Time

30 mins

### Links

- https://arxiv.org/abs/2304.07210

**Comment by jwrosewell** [comment]
See [European decision on the boundary between pseudonymisation and anonymization](https://www.lexology.com/library/detail.aspx?g=6d5b15d6-f956-4706-a3cb-c1e2da5e6505).

This agenda item only seems relevant if the group believe it has new information or considers itself a higher authority than the EU General Court. Does it?

**Comment by AramZS** [comment]
@jwrosewell - as has been previously stated this is a technical group, this proposal--as far as I can see--is to form a technical group. Not only does the EU General Court decision have zero relevancy to this process or this proposal (it is dealing with legal definitions of pseudonymisation and anonymization and notably does not specify technical methodologies to accomplish either process) it is also focused on an unrelated topic. Pseudonymisation is notably not mentioned here and the EU Court (as far as I can tell in a brief read, not being an EU legal expert, leaning only on my own experience) focus on it as a way to do share data that can be re-identified by a particular party. This proposal is specifically about assuring that anonymization does not fail to prevent identification by any party. Pseudonymisation is not even a topic at hand here.

To be clear, even if none of that were true, your comment would be irrelevant. We are not a court and we do not operate on behalf of a single country. This group has international membership. Questions of higher authority are irrelevant in the way you are asking. I assume EU judges mostly are not math and cryptology experts and similarly we are not legal experts. We do not operate in the same realm. Specification work must acknowledge that there are multiple countries that use the web platform and these countries' laws do not always match in legal regulation and that therefore the work we do is technical in nature and not legal. 

As I've stated before, if you want to argue about law with lawyers I believe you are attempting to establish a venue for that within the W3C. This is not that venue. If an EU court decides to come here and declare that the work of examining anonymization methods via a sub-group is somehow illegal we'd deal with that at that time, but seeing as they have not; and you are not--unless something has changed in your status recently?--a member of the EU Court or a representative of an EU judicial body I'm unclear on what grounds you have possibly reasoned that you are here to enforce your particular interpretation of EU law on this process.

Thanks for your feedback, as always, I enjoy reading the many things you have linked in this process.

**Comment by michaelkleber** [comment]
(FYI the Google folks attending the F2F next week do not include the authors of the paper that Graham linked to.  But I think Aram's "Would you like to discuss this during the upcoming F2F?" was about discussing _ organizing a sub-group_, not discussing the material this subgroup would be about, or the Topics paper in particular.)

**Comment by AramZS** [comment]
Yes, exactly thanks @michaelkleber. Sorry for my lack of clarity @grahammudd

**Comment by AramZS** [comment]
@jwrosewell I'm not really sure that is a good methodology for contribution, traditional practice is that the titles (since their character count is more restricted) are more simple then the post itself. I'd recommend reviewing the content of issues after the title before responding in the future or you may misalign your contributions. 

I don't believe dealing with privacy risk means that the only valid solutions are in engineering. But those are the solutions we're discussing here. Like I said, if you want to talk law with lawyers there are potentially other venues but you will neither find the right people nor the right context for that discussion here. 

> We have discussed making the input data required to implement the approaches advanced by this group available to all web participants. To do anything else is to "restrict competition" by restricting input data only to web browser vendors. That is a breach of the [W3C Antitrust Guidelines](https://www.w3.org/Consortium/Legal/2017/antitrust-guidance) and is not a choice you or the members of this group are free to make.

As has been previously stated, this is not the right venue to discuss your particular interpretation of antitrust and W3C policy. While there is an open thread on the question of "input data" that is the appropriate place for such discussion. This is not the appropriate thread for that discussion.

**Comment by AramZS** [comment]
> @AramZS Yes, we'd love to discuss during the F2F meeting. And yes, @michaelkleber the goal is discuss whether a sub-group effort would be worthwhile, not go deep on the paper or any method or technology.

Great, you are on the agenda @grahammudd !

**Comment by grahammudd** [comment]
Slides from yesterday are [here](https://docs.google.com/presentation/d/12GKopraPmYUFMk-Mp09uKOlofLSYXzBA_0AgRCb267I/edit#slide=id.p)

**Comment by grahammudd** [comment]
PDF version of the slides attached
[Discussion_  Measures of Empirical Privacy.pdf](https://github.com/patcg/meetings/files/11755527/Discussion_.Measures.of.Empirical.Privacy.pdf)

**Comment by jwrosewell** [comment]
Thank you for posting the slides including the reference to the regulator stakeholder group. The information I've provided will help the group understand their position which will be important to making the work understandable to them. I recommend soliciting their input upfront to avoid a disconnect.

**Comment by dmarti** [comment]
Suggested source related to this topic: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2756853

Best to avoid "privacy/utility tradeoffs" framing, when at least in some cases a higher "privacy" communication (sender of a message has less information about the recipient) has higher utility than a lower "privacy" (sender has more information about the recipient) alternative. A win-win is possible.

**Comment by grahammudd** [comment]
Great to see many of you last week in London.  
[@Tamara Greasby](https://w3ccommunity.slack.com/team/U0565QF1EJZ)
 and I are going to schedule a kick off meeting for the 'empirical privacy metrics' task force we [discussed](https://github.com/patcg/meetings/issues/129).  If you're interested in participating, please join [#patcg-privacy-metrics](https://w3ccommunity.slack.com/archives/C05CWDC4QP3)
