### ISSUE TITLE
Publish agenda in advance with links to relevant information.

### ISSUE THREAD

**Issue by bmayd** [patcg/meetings#13]
@AramZS @seanturner: Given that we're planning on having 2 days of long meetings, I think we ought to get an agenda which includes links to relevant documentation  published with as much lead time as possible so folks can come prepared. Starting with only the portion of the agenda already settled on and adding additional items as they are identified would be fine, but having at least a couple of days with the full agenda would enable us to get the most value from this group. If there is a mix of certain and possible topics, having them distinguished would also be helpful.

**Comment by AramZS** [comment]
I agree, as we get closer to a more fully fleshed out agenda I intend to update the repo with a more filled out version here: https://github.com/patcg/meetings/tree/main/2022/02/09-telecon - right now I have updated it with dates, but I will update it with the additional agenda items as they are fully fleshed out in the issues.

**Comment by AramZS** [comment]
Just noting that finalizing of the published agenda is reviewable at https://github.com/patcg/meetings/blob/Feb-09-Telecon-Agenda/2022/02/09-telecon/README.md
