### ISSUE TITLE
Agenda Open for TPAC Meeting

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#142]
Hi all! Our next meeting is at TPAC. Please add agenda items you'd like to discuss here!

**Comment by seanturner** [comment]
If you are presenting at TPAC, please use the following template for your slides:
 https://www.w3.org/2023/Talks/TPAC/Templates/

**Comment by benjaminsavage** [comment]
I would like to co-present (alongside the Singapore IMDA) on the results of our IPA pilot in the [IMDA PET Sandbox](https://www.imda.gov.sg/how-we-can-help/data-innovation/privacy-enhancing-technologies-sandbox). This presentation will include some details about which helper parties we worked with, how many row of data were in queries, how long queries took to run, estimated costs, but also regulatory clarifications from the IMDA on how they view the IPA proposal.

**Comment by marianapr** [comment]
Can we get a zoom link for the meeting for the ones joining remotely?

**Comment by seanturner** [comment]
Updated the meeting with links to Zoom and Minutes.  Note that these links are the same for both sessions.
