### ISSUE TITLE
Agenda Request - Discuss proposal to use Prio like architecture for advertising attribution

### ISSUE THREAD

**Issue by winstrom** [patcg/meetings#143]
## Agenda+: Discuss proposal to use Prio like architecture for advertising attribution

Apple WebKit has drafted a proposal to enable advertising attribution using Prio paradigms. The proposal issue can be found at https://github.com/patcg/proposals/issues/17 and the write up can be found at https://github.com/patcg-individual-drafts/private-ad-measurement. 

## Time

I imagine this would be a reasonably long discussion -- I would love as much time as you can give. 

### Links

Documents can be found at https://github.com/patcg-individual-drafts/private-ad-measurement

**Comment by martinthomson** [comment]
I want to suggest that we not take a ton of time for this.

We definitely should give Luke a solid chunk of time to go over the proposal in enough detail for people to understand its approach and philosophy.  But I would rather spend a larger chunk of time on a comparative exercise.  There are a number of areas where the different proposals are quite similar.  Exploring the major differences could help us make decisions about how to proceed.  THAT will be a long discussion, I expect.

**Comment by winstrom** [comment]
@martinthomson — this seems like a good suggestion. A small time for the presentation leading into a longer discussion of several ideas.

**Comment by martinthomson** [comment]
I've opened #144 to cover that.  @bmcase has been doing a ton of work there (I don't want to claim too much credit).

**Comment by AramZS** [comment]
@winstrom Are you ok presenting in the earlier session on Monday? I'd like to put you close to the top of our day.

**Comment by winstrom** [comment]
This is fine with me.
