### ISSUE TITLE
Agenda Request -  Results of IPA Pilot in IMDA PET Sandbox

### ISSUE THREAD

**Issue by richajaindce** [patcg/meetings#146]
## Agenda+: What do you want to discuss?

[@benjaminsavage](https://github.com/benjaminsavage) and I would like to co-present alongside the Singapore IMDA on the results of our IPA pilot in the [IMDA PET Sandbox](https://www.imda.gov.sg/how-we-can-help/data-innovation/privacy-enhancing-technologies-sandbox).
We would like to share about the test setup (details around which helper parties and report collector we worked with, how many row of data were in queries, noise added, etc) and results (how long queries took to run, estimated costs, etc). We will also go through the regulatory clarifications from the IMDA on how they view the IPA proposal.

## Time

30 minutes should be sufficient time to go through the content followed by discussion.

We expect time-wise split to be 
- Test setup + results : 10 mins
- Regulatory clarifications : 10 mins
- Discussion : 10 mins

### Links

Link to the slides: https://docs.google.com/presentation/d/1DmihkdxpBLNKyy6dxlgU8VSnp_EpveOJ6tqNfW8hU1I/edit?usp=sharing

PS: This is the same topic as what Ben had proposed in the comments [here](https://github.com/patcg/meetings/issues/142#issuecomment-1698311590).

**Comment by AramZS** [comment]
This sounds like a very interesting proposal. Let's reserve you 30m towards the top of the first session if that works? Are you ok with 10am Seville time Monday @richajaindce ?

**Comment by richajaindce** [comment]
Yes the time works for us :)

**Comment by richajaindce** [comment]
[Here](https://docs.google.com/presentation/d/1DmihkdxpBLNKyy6dxlgU8VSnp_EpveOJ6tqNfW8hU1I/edit?usp=sharing) is the link to the slides.
