### ISSUE TITLE
Agenda Request -  Complementary results on Private conversion measurement using label-DP

### ISSUE THREAD

**Issue by mvono** [patcg/meetings#148]
## Agenda+: Complementary results on Private conversion measurement using label-DP

In the last London PATCG meeting, Google presented some results on private conversion measurement using label-DP. Criteo obtained complementary results on the same public Criteo dataset by investigating:

- the impact of using a debiased loss function;
- the difference between Area Under Curve and log loss uplift compared to a naive model metrics;

We would like to present a summary of our findings and foster discussion on it.

## Time

10min presentation + 10min question

### Links

https://github.com/patcg/meetings/issues/128

**Comment by AramZS** [comment]
@mvono Would you prefer this to happen during TPAC?

**Comment by AramZS** [comment]
@mvono We can consider picking this up at TPAC if we have the time, but the Agenda is pretty full right now. As it stands I'd like to push this to our next meeting.

**Comment by mvono** [comment]
Hello @AramZS, if possible, yes I would prefer to present this during TPAC. Otherwise, it is OK to push this to the next PATCG meeting.

**Comment by AramZS** [comment]
@mvono Are you ok to present this in the upcoming PATCG meeting next week?

**Comment by mvono** [comment]
Yes

**Comment by AramZS** [comment]
@mvono Can we get your slides please?

**Comment by mvono** [comment]
[DP_PATCG.pdf](https://github.com/patcg/meetings/files/13186460/DP_PATCG.pdf)
