### ISSUE TITLE
Agenda Request - Mitigating the effects of ad fraud in measurement results

### ISSUE THREAD

**Issue by eriktaubeneck** [patcg/meetings#149]
## Agenda+: Mitigating the effects of ad fraud in measurement results

While working through the [Comparative analysis of measurement options](https://github.com/patcg/meetings/issues/144), we realized that this dimension was a fairly large topic on it's own which might help to have a dedicated discussion. The goal for the discussion would be to align on the various types of fraud that can effect measurement results, and if the ability to mitigate them is impacted by the various private ads measurement protocol designs.

## Time

45-60 minutes, split evenly between discussing the various types of fraud and the impact related to proposals. I'm sure the TPAC schedule is filling up quickly, and this is less important than the broader comparative analysis discussion, so I'd either put this at the end (which a chance it's bumped), or hold it until the next virtual meeting entirely.

**Comment by AramZS** [comment]
@eriktaubeneck I think it seems unlikely we'll get to this unless the comparative analysis runs unexpectedly short, but I will put it at the bottom of the Agenda and we'll call out at 45m before for people to consider the topic.

**Comment by eriktaubeneck** [comment]
Sounds good to me!

**Comment by AramZS** [comment]
@eriktaubeneck Are you good to present this next week?

**Comment by eriktaubeneck** [comment]
@AramZS we ended up talking about this a good amount at TPAC during the proposal comparison. Unless we're really struggling to fill the agenda, I'd propose we close this one out.

**Comment by AramZS** [comment]
Sounds good. Done.
