### ISSUE TITLE
Have a day free between meetings.

### ISSUE THREAD

**Issue by bmayd** [patcg/meetings#15]
I think I would get more out of these meetings and they would be less burdensome if we separated them by a day rather than doing them on consecutive days. Doing so would also give me a better opportunity to get feedback about day-one items from colleagues and give me a chance to balance focus with other things needing my attention.

Suggesting it for future meetings, not the February 9/10 '22 meetings.

**Comment by AramZS** [comment]
This is a good idea and we've aimed to do this in the upcoming meeting. I've seen no particular objections on that thread or here so I am going to take this as something we aim to do whenever people's schedules make it possible moving forward.
