### ISSUE TITLE
Agenda Request -  What data do we need to calculate the impact of use at scale? 

### ISSUE THREAD

**Issue by csharrison** [patcg/meetings#153]
## Agenda+: What do you want to discuss?

Brainstorm specific data that we should request from ads colleagues to help inform scale investigations on the various proposals. @thegreatfatzby and I were discussing this today. At TPAC this was mentioned but I think we probably need a bit more legwork to drill down into specific details.

## Time

1 hour

### Links

None right now, but closer to the meeting we might want to start brainstorming on a doc.

**Comment by AramZS** [comment]
@csharrison Looks good. Can you link the doc in advance and maybe include some of the issues in GitHub that you think make sense for informing such requests?

**Comment by AramZS** [comment]
I will lock the time into the agenda.

**Comment by csharrison** [comment]
Hey @AramZS apologies for the last minute change but could we move this to the agenda for the Dec meeting? There are still a few more things I need to do to have a productive meeting. I will try to share out an initial doc well in advance of the next meeting.

**Comment by ohpauleez** [comment]
Give me a shout @csharrison if there's anything I can do to help.  I'll be pretty busy over the next two weeks but then I should have some time

**Comment by bmcase** [comment]
I've thought a bit about this and what things we'd like to see, incomplete list:
1. for on-device proposals, knowing an estimate on the number of impressions/conversions per device per day would be helpful. 
2. the number of different histograms we want to see an attribution result contribute towards (for us this matters a lot we can have it large and used advanced composition to measure the budget across all)
3. knowing an upper bound on the number of histogram bins we might want in any histogram output (this will affect MPC performance in different designs)

To your latest comment Charlie, maybe we can have a short discussion to outline what things we'd like to go dig in more on.

**Comment by csharrison** [comment]
Ugh I apologize but I haven't made much progress since the last meeting. Let me see what I can do in the next couple of days but probably good to just allocate a small amount of time if any to this.

**Comment by csharrison** [comment]
Let's close it out for now. I can re-add if there is more here to discuss.
