### ISSUE TITLE
Agenda Request -  WALR - Weighted Aggregate Logistic Regression

### ISSUE THREAD

**Issue by benjaminsavage** [patcg/meetings#154]
## Agenda+: WALR - Weighted Aggregate Logistic Regression

We recently published a document that describes a new algorithm: [WALR](https://github.com/patcg-individual-drafts/ipa/blob/main/logistic_regression.md). This is a proposal for how to train a Logistic Regression model *in MPC*. This is a alternative approach to machine learning that can be viewed as an alternative approach to the "noisy labels" approach we have previously discussed in this group.

With this approach, no individually linkable outputs are required. The algorithm only produces aggregate data which are essentially averages across the entire population. Of course, these are made differentially private as well to provide robust privacy protections.

Logistic Regression is not a very complex or sophisticated type of "machine learning", but it has several major benefits:

1. **Simplicity:** Logistic regression is a simple and interpretable algorithm, making it easier to understand and explain. Deep learning models can be highly complex and challenging to interpret.
2. **Computationally Efficient:** WALR provides a computationally efficient approach to performing Logistic Regression in MPC. Training a deep learning model requires significant computational resources even when performed in the clear. Training in MPC will likely require orders of magnitude more computational resources.
3. **Smaller Data Volumes Required:** Logistic regression works well with smaller datasets, whereas deep learning typically requires large volumes of data to perform effectively. In cases where data is limited, logistic regression may be a more practical choice.

## Time

Estimated time by section:

1. The high level objective, output of WALR, and how to interpret it: 10 minutes.
2. The derivation of WALR, and how it is implemented in MPC: 10 minutes.
3. Q&A: 10 minutes.

### Links

- What is "Logistic Regression"? [Link](https://simple.wikipedia.org/wiki/Logistic_regression)
- Explanation of WALR algorith: [Link](https://github.com/patcg-individual-drafts/ipa/blob/main/logistic_regression.md)

**Comment by AramZS** [comment]
Looks good. I'll add it to the agenda.
