### ISSUE TITLE
Agenda Request -  2024 Meet Locations

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#157]
## Agenda+: 2024 Meeting Locations

We need to discuss where our F2F meetings in 2024 might occur.  Some options that have been suggested: Singapore, Boston, LA, Cologne.

## Time

Definitely a Day 2 Topic!

15min

### Links

N/A

**Comment by AramZS** [comment]
Oops meant to include this after our last discussion. Added to the agenda

**Comment by rachelyager-nyc** [comment]
@AramZS @seanturner   I can support hosting 2024 F2F Meetings in New York City and Singapore. We can discuss it and plan the meeting agenda/dates, capacity, and logistics requirements.

**Comment by alexWhitworth** [comment]
If we can have the F2F meeting be on consecutive days (vs Tu/Th), it will be easier for those of us on tighter travel budgets.

**Comment by seanturner** [comment]
@rachelyager-nyc pinng me when you get a chance via slack or email.
