### ISSUE TITLE
2024 F2F Meeting Locations

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#160]
# REVISED 20240201

We are proposing to meet once more F2F in 2024 in additional to the [TPAC 2024](https://www.w3.org/events/tpac/2024/). TPAC 2024 is scheduled for 23-27 September 2024 in Anaheim, CA, USA. This plan includes one less F2F meeting than we had discussed in October; scheduling two F2F meetings prior to TPAC was proving difficult.

I have a firm commitment for a meeting location in Boston that meets our requirements that includes support for remote participants. As noted in #159, we are proposing that the meeting be held April 9 & 10 (Tuesday & Wednesday).  We also have alternative dates, but I am hoping that this is enough lead time and the dates don't clash with anything so that this time will work.  And, I am also hoping that we will be meeting as a WG too.

**Comment by csharrison** [comment]
Sean I think you need to open up permissions on the form.

**Comment by seanturner** [comment]
Sorry about that I think I've opened it up.

**Comment by seanturner** [comment]
Also, looking at sliding June to the next week see comments in #159.

**Comment by samuelweiler** [comment]
Please fill out the [survey](https://forms.gle/RVcWFzYzzRmV7i3e9) about F2F meeting locations for 2024.  Note that the checkbox question is "which of these places would you be willing to go?", not "what is your preference?".   Feel free to add a preference in the free response field.

**Comment by eriktaubeneck** [comment]
> Face-to-face meetings that require separate travel from a larger meeting (like TPAC) seems unusual and costly for participation in a Community Group. Are these proposals for f2f meetings for a Working Group?

For clarification, these are intended to be hybrid, not exclusively f2f. Last year we also had 2 hybrid meeting apart from TPAC, NYC in the winter and London over the summer, and I think the general feeling was that they were exceptionally productive relative to the exclusively virtual meetings. 

My understanding is that these are intended for the community group, not the working group.

**Comment by seanturner** [comment]
Yes - we have some requirements for the F2F meetings, i.e., ~50 attendees, no NDA, and remote participant friendly, so they are in fact hybrid meetings.

As we have no WG right now, the meetings are for the CG, if the WG gets chartered then we can decide whether we would like to make these WG meetings.

**Comment by seanturner** [comment]
Please check out the 1st post in this PR for an update on the proposed meeting location.

**Comment by martinthomson** [comment]
In terms of clashes, the [W3C AC Forum meeting on April 8 and 9 in Hiroshima](https://www.w3.org/2024/04/AC/Overview.html) (sorry, member-only link) is probably one of the more awkward ones.

I am guessing that PATCG will win out for most people, but I know that we have a few people who are affected.  I believe that the W3C Board of Directors and Advisory Board also intend to meet.  At least for me, I'm thankful that the the TAG decided against having another face-to-face, despite being encouraged to.

**Comment by seanturner** [comment]
Yeah that's a pretty bad clash.  I did get alternative dates for the week earlier.  Not sure if that helps much though because people are would be starting out on the road.

Alternatively, we just do it virtual the week before.

**Comment by hober** [comment]
> In terms of clashes, the [W3C AC Forum meeting on April 8 and 9 in Hiroshima](https://www.w3.org/2024/04/AC/Overview.html) (sorry, member-only link) is probably one of the more awkward ones.

Yeah, this is a hard conflict for me.

**Comment by seanturner** [comment]
Hi! The meeting locations/times are set for 2024. I plan to close this issue out on 23 August unless there are objections.
