### ISSUE TITLE
Form Agendas for Dec 5/7 meeting

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#161]
Hi all, I'm putting a call out for adding agenda items for the meetings on Dec 5 and 7. Please open issues for what you want to discuss. The window for this is narrowing as I'll be locking in the Agenda soon.

**Comment by AramZS** [comment]
Agenda is live and don't forget that we are in the Sydney and Tokyo friendly timezone tomorrow (/today if you are on the US west coast).

**Comment by seanturner** [comment]
****
**** We December 7th call was canceled.
****
