### ISSUE TITLE
Agenda Request -  Update on IPA implementation

### ISSUE THREAD

**Issue by akoshelev** [patcg/meetings#165]
## Agenda+: Update on IPA implementation 

We want to give an overview of the progress we've made so far working on the implementation of IPA. We were able to reduce the algorithmic complexity of malicious security and improve both throughput and latency of IPA through many code optimizations. In this presentation we want to update the CG on the latest performance metrics we got from running a malicious MPC and discuss the next improvements we plan to work on in the nearest future. 

## Time

30 mins

### Links

[IPA implementation](https://github.com/private-attribution/ipa)
[Slides](https://docs.google.com/presentation/d/1-ACeAWI0EdD8gNBDLVjPfMT1eHEK8fbNzjXgMcco8Cs/edit#slide=id.p)

**Comment by AramZS** [comment]
Added to the Agenda
