### ISSUE TITLE
Request for an Ad-Hoc Meeting On: Effect of Noise on Advertising Decision Making

### ISSUE THREAD

**Issue by eriktaubeneck** [patcg/meetings#169]
## Effect of Noise on Advertising Decision Making - Planning Test Design Proposal

In the Oct 2023 meeting, we discussed #155 on an experiment to better understand the effect of DP noise on advertising decision making. I'd like to invite others to help incorporate the feedback from that session and work on a test design proposal which can be presented and discussed at the April 2024 F2F.

## Timing

Wed, March 13th at 2:30pm-3:30pm PT. ([See here](https://everytimezone.com/s/1c92d046) for other timezones.)* (Note: this is postponed from the original date, March 6th.)

[Zoom link](https://fb.zoom.us/j/96977191108?pwd=RXoxNjlZWDBZK3pFWVNrQzh4aTA3dz09)

This is currently a one-off, but if the group see's fit, I'm happy to organize another meeting before the April F2F.

*If you have a major conflict and would like to attend, please post in the comments with alternatives, and if needed I can start a poll.

## Links 

See #155 for initial issue, and minutes ([day 1](https://docs.google.com/document/d/1X1mq_aK8sDlVZiMcaY-GmHt9d6bbIwWen913KGeVed4/edit#heading=h.59agjfp99eu2) and [day 2](https://docs.google.com/document/d/1X1mq_aK8sDlVZiMcaY-GmHt9d6bbIwWen913KGeVed4/edit#heading=h.x7i4e6ucen1a)) from the Oct meeting.

Also see https://dp-game.vercel.app/ for the current prototype game.

**Comment by bmayd** [comment]
Will details be published in this issue as they're finalized?

**Comment by eriktaubeneck** [comment]
@bmayd details on the ad-hoc meeting, or details of the outcome of the meeting?

for the meeting itself, consider this timing finalized unless updated on this issue.

for the outcome, the intention is to present at the April F2F.

**Comment by bmayd** [comment]
Details on the meeting, link to it in particular.

**Comment by eriktaubeneck** [comment]
Yes, will share on here shortly.

**Comment by eriktaubeneck** [comment]
Apologies folks - I need to postpone this by 1 week. I've updated the original comment with the new date, March 13, and added a Zoom Link. cc @bmayd

**Comment by bmayd** [comment]
@eriktaubeneck Thanks. Suggest you add a note under Timing, above indicating that the date was originally March 6th to avoid confusion.
