### ISSUE TITLE
Private Measurement Review

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#17]
## Review presentations and concepts on private measurement

30m-1h length. We will discuss constraints, conditions and comparisons between private measurement proposals following a longer discussion from proposal authors to start the process of understanding these proposals and how to move forward with work on a private measurement standard. 

@erik-anderson has suggested that a member of the Microsoft team may be interested in presenting a comparison during this time slot. 

### Links

This follows and builds on https://github.com/patcg/meetings/issues/9

**Comment by erik-anderson** [comment]
As noted in https://github.com/patcg/meetings/issues/9#issuecomment-1033097621, we'd be happy to provide a high-level comparison between proposals as we understand them.

If other folks have similar comparisons they'd like to present it would be good to provide them an opportunity to do so as well.

**Comment by AramZS** [comment]
@erik-anderson I think that would be useful. Would your person be ok doing their overview in 15m at the top of this section (giving time for discussion following)?
