### ISSUE TITLE
Agenda Request+: TPAC 2024 Planning

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#174]
## Agenda+: What do you want to discuss?

Need to gauge whether there is interest in trying to schedule an all-day PATWG meeting Friday.  I have been lead to believe that we have a much greater chance of having our request granted if the meeting happens on Friday.

## Time

10min somewhere near the end of the agenda.

### Links

[TPAC 20244](https://www.w3.org/news-events/w3c-tpac/#upcoming-tpac-2024)

**Comment by myonlinematters** [comment]
Hi Sean!  I am confused.  Is this in leui of the Tue/Wed F2F or is it an additional or separate meeting?  F2F or online?

**Comment by eriktaubeneck** [comment]
@myonlinematters - not Sean, but it seems this would be as part of TPAC, the annual full W3C meeting that will take place Sept 23-27 in Anaheim, CA (with a virtual meeting.)

@seanturner: voicing initial support for this. Last year at TPAC we wished we had more time, so I imagine a full day would be fruitful this year.

**Comment by thegreatfatzby** [comment]
Hey @seanturner I see right now we have a "tentative" slot for Friday...is that basically locked in?
