### ISSUE TITLE
Agenda Request -  Hybrid Proposal Design

### ISSUE THREAD

**Issue by bmcase** [patcg/meetings#175]
## Agenda+:  Hybrid Proposal Design
The teams from Meta and Mozilla would like to share a new hybrid proposal for private ads measurement.  As shown in the [IPA-PAM-ARA comparison work](https://github.com/patcg/meetings/issues/144), no proposal has the advantage in all of the key dimensions. We would like to propose a hybrid proposal that builds upon the strengths of the previous proposals PAM, IPA and summary ARA.  In particular, our goal is to keep the data minimization and explainability of PAM and combine it with the delay-related and fraud mitigation advantages of IPA. PAM and IPA both in turn build on many of the ideas from summary ARA in doing on-device attribution and outputting aggregated histograms.

We achieve this hybrid by using short-lived random identifiers (impression-specific match keys) generated by the device. Attribution and DP budgeting can remain on device while impression and conversion reports can be generated and sent off the device without delays and joined together using the random identifiers in an MPC reminiscent of IPA.

We have three documents to share

1. [Proposal](https://docs.google.com/document/d/1dLaQstrLqV7PEKqCr6F9wQ4I5hNKvT4iF6J-ng5jhas/edit?usp=sharing)
2. [Presentation](https://docs.google.com/presentation/d/1yl_yIVM2QGDegpanyPqhZ40QGJKD1AZQjIadbV6VDbQ/edit?usp=sharing)
3. [On-device DP budget management](https://docs.google.com/document/d/11BWNzkaTSAa6ZBzl6fbbnpLZi8vgSZjcqKYIt84HXko/edit?usp=sharing)

The DP budget management is work done together with Roxana Geambasu and her research team.  There is still work in progress to fully align the theory of on-device DP budget management with all of the setup of this hybrid design; we try callout throughout where there is still work TBD. 

## Time Requested: 2hrs Tuesday + 2hrs Wednesday
It would be nice if we can spend a lot of time in Boston discussing this.  We propose to break the discussion into two main sections: 
1. On Tuesday we can give an overview of the proposal using the above presentation and have discussion.  We should probably take about 2hrs for this. 
2. On Wednesday we’d like to have another 2hr slot to present the DP budget management work and have discussion (we’ll share some more slides for this before the presentation). 

## Links
Links to the three documents are above.  We will also work on uploading copies of these docs in a new individual drafts folder so we can have a more organized place for folks to file issues relevant to this hybrid proposal.

**Comment by AramZS** [comment]
Big chunk of time! Ok, we'll reserve.

**Comment by bmcase** [comment]
Thanks @AramZS!

**Comment by bmcase** [comment]
Added link to DP presentation [slides](https://docs.google.com/presentation/d/1osP7A04J-jmfg_c5FxQutLplLDpuWV6NC685kGTIYT8/edit#slide=id.g2c9a1d0d3f0_0_0). 

Also created individual drafts folder: https://github.com/patcg-individual-drafts/hybrid-proposal
