### ISSUE TITLE
Agenda Request -  Global and Local DP impact for learning bidding models

### ISSUE THREAD

**Issue by mvono** [patcg/meetings#179]
## Agenda+: Global and Local DP impact for learning bidding models

Criteo ran several experiments to learn bidding models using either local DP (event-level reporting) and global DP (learning inside a trusted server or via an aggregation API). We notably tested the impact of the noise level associated to the value of epsilon. We would like to present our findings and foster discussion.

## Time

30min

### Links

None

**Comment by AramZS** [comment]
Moved this up to the 13:30 slot @mvono if that's ok.

**Comment by AramZS** [comment]
@mvono Please add slides when you have a chance.

**Comment by mvono** [comment]
[PATCG_Boston_private_learning.pdf](https://github.com/patcg/meetings/files/14936682/PATCG_Boston_private_learning.pdf)
