### ISSUE TITLE
Schedule next meeting

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#19]
## At the end of the upcoming meeting we should determine the time for the following meeting and related topics

This is an agenda item to mark that we will be discussing the following meeting timing and participation as well as future topics for that meeting. I've set up [a label for issues that are potentially up for discussion for following meetings](https://github.com/patcg/meetings/labels/agenda%2Bnext) and we can briefly (no more than 30m) talk through what we intend to discuss--in the knowledge that it is just a leaping off point for further discussion on this issue asynchronously after the meeting.

**Comment by bedfordsean** [comment]
As one further point on this (super minor) I'd like to discuss timezone logistics. I was under the impression we were going to alternate for one "super bad" timezone per region. 

This is the third meeting and we've gone "bad for EMEA" > "bad for APAC" > "bad for EMEA". I think for equality we should have probably done a "bad for NA" (3 way rotation) rather than a 2 way rotation.

**Comment by jalbertoroman** [comment]
at least would be great to have recording. In Europe today starts at 00:00 am

**Comment by eriktaubeneck** [comment]
@jalbertoroman see #10 for the discussion around recording. It's both not viable by W3C rules (linked in that issue) as well as opens some real accessibility issues for some who face harassment online (also discussed in that issue.) As such, the group has decided to not have recordings and is considered a closed issue.

@bedfordsean this was what I proposed (also in #10), and as someone from NA, I'm happy to have my share of badly timed meetings.

**Comment by seanturner** [comment]
@bedfordsean We can do the next one at 1100 (PDT), 0200 (EDT) (next day), 0600 (UTC), 1400 (Signapore), 1600 (AEST).

**Comment by bedfordsean** [comment]
Thanks @seanturner - I think that's as "fair" as we can make it to maximise for all regions!

**Comment by bmayd** [comment]
@seanturner 
> We can do the next one at 1100 (PDT), 0200 (EDT) (next day), 0600 (UTC), 1400 (Singapore), 1600 (AEST).

Is that 2300 (PDT)?

**Comment by bedfordsean** [comment]
> Is that 2300 (PDT)?

Yes, in 24h time I assume so based on the 0200 EDT :-)

**Comment by seanturner** [comment]
Yes. That was me messing it up (always a problem).

**Comment by aphisit182534-ui** [comment]
chrome://policy in the password 🔑
