### ISSUE TITLE
Agenda Request - Attribution Level 1

### ISSUE THREAD

**Issue by martinthomson** [patcg/meetings#191]
## Agenda+: Proposal to start work on a "level 1" attribution API

We've spent a lot of time working out the details of what might fall into that very small space where privacy and utility meet.  There have been a lot of discussions about what might be, what requirements need to look like.

Those have all been constructive discussions, but some of us are tired of the talking and want to start doing something.

We'd like to spend a good chunk of our face to face time talking about a plan.  That staged plan will start with a proposal that we hope will meet privacy constraints, but is likely to leave a bunch of utility unrealized.  We'll call that the "level 1" of the API.

The idea is not to meet all of the diverse advertiser needs that we've identified, but to slice off something significant that might enable the most basic reporting use case and maybe a tiny piece of the optimization story.  Then, we have a common base from which to iterate and improve.

We've started work on writing this up over [here](https://private-attribution.github.io/api).  This is very rough today, but our goal is to have enough sketched in before we meet that we will be able to discuss something concrete, rather than deal in abstractions.

We know that there are lots of things that need to be expanded upon to get something that is closer to the sort of utility that is presently achievable with ARA, or what was promised by IPA.  We plan to track those in a "level 2" companion that will progressively add those features as they mature.

Our goal is to reserve some amount of time on an ongoing basis to develop those "level 2" ideas to the point that they can be integrated progressively as they mature.  That is, excluding capabilities from a "level 1" effort doesn't mean we won't work on that, just that we aren't committing to delivery until we better understand whether it will be deployed in multiple implementations.

## Time

We think this will take a couple of hours to present a more detailed plan and then discuss what to do.  Our rough plan is to:

1. Outline the core of the "level 1" proposal, what we think is an achievable scope, where we have uncertainty, and what we'd prefer to defer to "level 2" or later. @martinthomson will lead this part.
2. Go through some of those items that we think can be deferred in some more detail.  The idea here is to try to outline the risks and reach agreement on whether to defer each. @benjaminsavage will lead this part.
3. Reach agreement on the plan and recruit people to help.  Either of us is happy to lead, but we think that the chairs might be in a better position for that.

Ideally, we'd like to have this run in a couple of chunks, with breaks so that people can spend some time working through the details.  An hour each for the first two would be ideal, with slightly less for the last. I realize that we have other time pressures, so any time that is available would be welcome.

### Links

https://private-attribution.github.io/api

**Comment by AramZS** [comment]
@martinthomson we're giving the group about 2 and a half hours for this.

**Comment by bmayd** [comment]
> https://private-attribution.github.io/api

I get a 404 when I try to load this link mentioned above, is the writeup no longer available?

**Comment by eriktaubeneck** [comment]
@bmayd it's now hosted at https://patcg.github.io/ppa-api/ as it's been moved into the PATCG org. Github pages unfortunately does not automatically redirect in the way the actual repository does.

**Comment by bmayd** [comment]
Thanks @eriktaubeneck!
