### ISSUE TITLE
Agenda Request -  Participating in PATWG

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#202]
## Agenda+: What do you want to discuss?

Explain how to join as a W3C member and how to apply to be a IE (Invited Expert) if not a member

## Time

20 minutes.

### Links

If a W3C member, please use this [link](https://www.w3.org/groups/wg/pat/instructions/).

If not a W3C member, please use this [link](https://www.w3.org/groups/wg/pat/instructions/).

**Comment by myonlinematters** [comment]
@seanturner - application to join the group subitted.
