### ISSUE TITLE
Call for Scribes - 2022-02 Meeting

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#22]
## Looking for participants who will volunteer to take active notes

Please comment on this issue if you are willing to scribe notes actively during the meeting. If you are only able to scribe one of the two days, please note that. If possible it would be nice to switch scribes per-hour.

Thanks!

**Comment by bedfordsean** [comment]
I'm happy to scribe for the first hour of today and tomorrow. It's late for EMEA so my ability to listen+write is probably going to rapidly diminish beyond the first hr or so of each session!

**Comment by npdoty** [comment]
I'm happy to help scribe, any timeslot.

**Comment by stumakha** [comment]
I can do today in the last hour.

**Comment by michaelkleber** [comment]
I can do an hour.  Prefer one of the Measurement+Attribution hours, where I'm more likely to listen than talk.

**Comment by markkent** [comment]
I can also help, any timeslot.

**Comment by seanturner** [comment]
Here's is the link for dDoc for the [minutes](https://docs.google.com/document/d/1ZH_UOOMSFG5X-l72wIFeQ7h69FFi5S_R_eTyH5JYm4I/edit?usp=sharing). 

Will also share once we start up the session.

**Comment by seanturner** [comment]
I see others there so it appears that I set the permissions correctly.

We will convert these to markdown and post them in the meeting repo as well as get them link on the patcg W3C calendar for future reference.

**Comment by AramZS** [comment]
I would love to see someone take over from @bedfordsean for hour 1 of day 2, but for now here's the scribe order. Thank you very much to those who have volunteered! 

### Day 1:
Scribe 1: @bedfordsean
Scribe 2: @npdoty
Scribe 3: @stumakha

### Day 2:
Scribe 1: @bedfordsean
Scribe 2: @michaelkleber
Scribe 3: @markkent
