### ISSUE TITLE
Secret ballots

### ISSUE THREAD

**Issue by jwrosewell** [patcg/meetings#26]
Some people may not feel comfortable engaging in debate either verbally or via comments. In order to ensure their views can be considered I request that the Chairs use secret ballots as a method of testing consensus.

**Comment by AramZS** [comment]
The charter states that we will define consensus under the principles of [RFC 7282](https://datatracker.ietf.org/doc/html/rfc7282). Paragraph two states that this style of consensus is not found via ballot. This proposal does not fit within the chartered behavior of this group. Further proposals on how to achieve consensus should operate within the framework informed by the document cited by our charter. Thank you for the suggestion but this will not work with our group as chartered.

**Comment by jyasskin** [comment]
For what it's worth, if someone is uncomfortable publicly expressing and explaining their opposition to an apparent consensus, I'd encourage them to contact the chairs about what to do. Intimidation is prohibited by the [CEPC](https://www.w3.org/Consortium/cepc/#unacceptablebehavior), and we wouldn't take action against anyone for disagreeing with a proposal, but it's important to find ways to hear the opinions of even people who don't believe me. I do doubt that any such people exist, but I support them having a way to express themselves if they do.

**Comment by jwrosewell** [comment]
I don't want to risk CEPC violation by posting evidence here. Shame secret ballot is not allowed for and too late to address. Hopefully W3C Process will be updated to allow [anonymous Formal Objection](https://github.com/w3c/w3process/issues/497) before Working Group charter vote.
