### ISSUE TITLE
Should we already have a separate repo for discussing measurement?

### ISSUE THREAD

**Issue by erik-anderson** [patcg/meetings#33]
Last week, we spent 6 hours meeting to discuss a variety of measurement proposals. One outcome of that meeting was to discuss in more detail via additional GitHub issues.

It's not clear to me that issues in this repo ("meetings") is the appropriate place since many of the discussions aren't tied to meeting requests and potentially will never turn into meeting agenda topics. I worry that planning for the next meeting will be made more difficult if the meetings repo becomes the general place for discussion and other unrelated-but-important topics may get buried.

Where do we want to open issues to discuss different aspects of the measurement proposals? Would a separate repo to hold issues focused on that general topic be better? Or do folks prefer to keep opening additional issues here?

**Comment by AramZS** [comment]
Chairs agree and I will set up the space now!

**Comment by AramZS** [comment]
The repo is up, but I would request that we refrain from using it until the W3C configuration has been updated to send changes and issues to the mailserv. I will note when that setup is complete here.

**Comment by AramZS** [comment]
The space is now open for business and on listserv. Additionally I wrote up some useful issue templates that may help structure the discussion. Please PR or let me know if there are additional templates that might help in that space. You can use it at https://github.com/patcg/private-measurement
