### ISSUE TITLE
April 2022 Meeting

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#34]
[Please fill out this link to indicate your availability.](https://doodle.com/poll/qd6f6smxbhfxiw2f?utm_source=poll&utm_medium=link)

Aram and I would like to schedule the next patcg meeting for either the 1st week (4-7) or 2nd week (11-14) of April.* We thought the two 3 hour sessions worked well so we will try that again. As agreed, we are going to rotate the time of day around so that at some point everybody will need to be up late.  This time we are proposing [2300 AEST / 2100 Singapore / 1500 CEST / 1400 BST / 1300 UTC / 0900 EDT / 0600 PDT](https://everytimezone.com/?t=624a3500,30c). We will look at having a day in between to allow for discussion, as suggested by Brian May in Issue #15.

The purpose of the meeting is to continue discuss we started in February. A more detailed agenda will follow.

* Exactly 6 weeks away from our last meeting is the IETF week. And, at 8 weeks from our last meeting we can use the time change in Australia to our advantage.

**Comment by seanturner** [comment]
# REMINDER

[Please fill out this link to indicate your availability.](https://doodle.com/poll/qd6f6smxbhfxiw2f?utm_source=poll&utm_medium=link)

There are currently 12 participants at this point. There were 80ish participants at the last meeting.

Would love to be able to pick the time by 9 March 2022.

**Comment by marianapr** [comment]
Hello, is it possible to add the third week of April as an option? April 11-14 collides with Real World Crypto (https://rwc.iacr.org/2022/) that some of the participants might be attending

**Comment by seanturner** [comment]
Right now the 5th and 7th seem to be the days that where we have the most positive responses. Unless there are some drastic changes soon that looks like the days we will settle on.

**Comment by seanturner** [comment]
I will also announce this over in the admin repo, but we have settled on April 5th and 7th based on the doodlers. Thanks to all who participated.

**Comment by seanturner** [comment]
I have also create this [repo](https://github.com/patcg/meetings/tree/main/2022/04/05-telecon) for the meeting to capture the agenda, presentations, etc.

**Comment by marianapr** [comment]
Do we have time of the meeting on April 5 and April 7?

**Comment by AramZS** [comment]
9am to 12pm ET with times translated here - https://everytimezone.com/?t=624a3500,30c @marianapr

**Comment by AramZS** [comment]
Noting a draft of the agenda here - https://github.com/orgs/patcg/projects/2

**Comment by AramZS** [comment]
Agenda is drafted here - https://github.com/patcg/meetings/pull/45
