### ISSUE TITLE
Meeting Cadence and Timing?

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#4]
Hello all, 

After our excellent discussion at TPAC today I wanted to open the thread to discuss time and cadence of our meetings. 

There are two main issues:

## Issue 1: Cadence

Initially I thought a weekly meeting might be best but there has been some excellent feedback from the group that suggested a less frequent cadence with a longer meeting time. I'd like to see feedback in support of either here:

Option **A**: Let's use the assumption that a less frequent meeting time might mean a 3-4 hour meeting on a monthly basis. We'll start that cadence virtually and assume that some of those will move to F2F once travel restrictions and health concerns start lessening to a reasonable state. (I would think perhaps every other quarter, but please give options if you think otherwise). It may also make sense to rotate the timing of this one between APAC and EMEA friendly times as well, each month.

~~Option **B**: A weekly meeting that rotates time to switch between APAC friendly and EMEA friendly with a day-long F2F once travel restrictions lessen  (I would think perhaps every other quarter as well in this case, but please give options if you think otherwise).~~ _(Option B removed to reflect the discussion as it stands - Aram ZS)_

Option **C**: Propose another option if preferred.

## Issue 2: Timing 

I think to be as able to gather as many interested folks as possible we will likely need to rotate any cadence between APAC- and EMEA-friendly times. This would be more explicitly required by Option B above, but likely needed overall. I'll note that both chairs are in Eastern time, but have also both expressed a great deal of timing flexibility. I think that, if possible, we should avoid overlapping with WebAdv, PING or PrivacyCG, as those groups have a great deal of overlap with us in membership and purpose. If there are any other common meetings we would like to avoid, please let us know. 

WebAdv: Tuesday 11:00 EDT / 15:00 UTC / 23:00 CST / 02:00 AEDT
PING/PrivacyCG: Thursday 12:00 EDT / 16:00 UTC / 00:00 +1 day CST / 03:00 +1 day AEDT

If we do go towards longer meetings, which is what it sounds like this group might be leaning towards, we should take into account the start and end time for both. 

For days: I am inclined towards Mon/Tues/Thurs as potential target days of the week. 

Once we've determined cadence I'll edit and place a link to a Doodle in this issue to help with the planning for timing.

**Comment by michaelkleber** [comment]
Note some discussion already in https://github.com/patcg/admin/issues/2

**Comment by npdoty** [comment]
A useful theme from today's discussion was that it can be more efficient to go longer between longer-duration meetings for groups that have a shared sense of technical goals and deliverables and active, effective asynchronous work.

I don't think we have that shared sense yet. I literally don't know what the work items for the group are, and I think going several weeks before we talk about that again would put anyone who doesn't have that shared sense at a disadvantage. But if we do get into that work mode (because we have basic agreement on the principles doc and we have a core set of adopted proposals that we are working on), then I think we could productively shift to infrequent meetings.

**Comment by npdoty** [comment]
I think frequent (every few months?) face-to-face meetings are both infeasible for the indefinite future and also extremely expensive -- in terms of financial investment, time spent traveling and carbon emissions -- once travel and meeting restrictions are lessened.

I don't think we should plan to rely on those meetings, but if necessary, I hope we will very seriously consider access for those who can only attend virtually.

**Comment by eriktaubeneck** [comment]
Some of the potential working items (like the [Attribution Reporting API](https://github.com/WICG/conversion-measurement-api/issues/80) and [MPC for measurement](https://github.com/WICG/privacy-preserving-ads/issues/39)) already have semi-regular meetings scheduled.

Maybe this is already assumed, but it would make sense for people who want to work closely on work items to have more regular meetings to make progress, and the less regular, full group calls, can help bring the full group up to speed on that progress.

**Comment by csharrison** [comment]
+1 to Erik I was going to suggest this on the call. I think we need to balance making more rapid progress on some work items and making sure people don't need to juggle multiple different tracks to stay up to date. The IETF "design team" format might make sense to adopt where work in these breakouts is subject to broader consensus in the regular scheduled calls.

Happy to hear others' thoughts though.

**Comment by martinthomson** [comment]
As I said on #2, my ability to participate in those existing meeting is zero, despite a keen interest in doing so. That groups regularly meet in this way is a problem, not a solution.

**Comment by eriktaubeneck** [comment]
@martinthomson, my hope is that if we have somewhat small groups for work items, those groups can find times / work modes that work well for those participants. I fully support revamping those meeting times to a time that will work for you and others invovled.

**Comment by AramZS** [comment]
Yeah, I agree with most of what is said here but I am inclined to lean towards @martinthomson's position that the split off meetings for individual proposals is part of the issues around tracking and contributing to those proposals that we intend to resolve by bringing those discussions into a regular conversation through this group. And I think that @npdoty is correct that longer time than a month between meetings is an idea that makes sense once the work mode and focus is better set, we still have some initial setup to do, including conversations about specific proposals to focus in on and setting up editors and projects. I think we should anticipate some more frequent meetings while we get ourselves up and running and then a move to less frequent meetings. 

@eriktaubeneck It would also be helpful to get a sense of the frequency at which these split off meetings turn around changes or activity that this group might discuss? I've only managed to get to a few of them with my own schedule so I'm not as familiar with their activity as you are. What do you think is the frequency they might generate changes which we would want to discuss? 

I also think that I am seeing a significant convergence on less frequent meetings and no support for weekly here or in https://github.com/patcg/admin/issues/2. Especially considering the increased stress it puts on the set of diverse timezones in which are participants are active.

At this time, it is reasonable to drop option B from the top of the thread. (I will edit it to reflect that)

For the question of timing, would an initial monthly meeting to set up our work at a shorter amount of time (say 2h) seem reasonable for the first few meetings to all? I am hesitant to move to any less frequency than that at the initial setup stage we're at right now.

**Comment by lukwlodarczyk** [comment]
I strongly support virtual access for participants not attending f2f meetings if we decide about the operational mode in the future.

Smaller tech companies that are based outside the US will meet constraints that might, in consequence exclude them from collaboration.

1. Regulatory travel constraints. COVID border restrictions, visa etc.
2. Additional expenses. Flights, accommodations etc.
3. Time spent on travelling.

The current virtual working mode allows for diverse participation without sacrificing any day to day responsibilities. It is essential for smaller-tech participants.

I am a big fan of monthly meetings with carefully selected working items in advance, allowing all participants to prepare a meaningful discussion. Therefore, two hours for the first meetings seems reasonable.

It would be great to start a specific issue allowing us to build the first agenda meeting where all submitters will also decide how much time they need to consume from the overall meeting time. It might help us in estimating the length of the "second first" meeting.

**Comment by dialtone** [comment]
Is there a zoom link or details about this call? I can't find this information anywhere, somewhere it links to the TPAC call information but that page now says that the call is finished.

**Comment by bslassey** [comment]
> I also think that I am seeing a significant convergence on less frequent meetings and no support for weekly here or in [patcg/admin#2](https://github.com/patcg/admin/issues/2).

I see support from both @csharrison and @eriktaubeneck to have more frequent calls to discuss more tightly scoped topics. We obviously need to sort out our work mode, but it seems like any products of those discussions can be confirmed on the email list.

**Comment by marianapr** [comment]
It will be great if we can form a work stream that focusses on technical side of MPC design proposals for privacy preserving functionalities of interest, which was the goal of the meeting that Erik posted above https://github.com/WICG/privacy-preserving-ads/issues/39. The sentiment during the meeting was that PATCG might be the right place for this discussion.

**Comment by alextcone** [comment]
@AramZS @seanturner - is this the right thread to watch for a decision that will lead to an initial meeting being set (not counting the TPAC kickoff)?

**Comment by seanturner** [comment]
Yes, but note that we will advertise the decision on the W3C mailing list.

**Comment by AramZS** [comment]
> @AramZS @seanturner - is this the right thread to watch for a decision that will lead to an initial meeting being set (not counting the TPAC kickoff)?

Yup!

**Comment by seanturner** [comment]
Please note that Aram and I have suggested a virtual meeting in January, see #5. That meeting will allow us to discuss the outstanding proposals and hopefully provide a little more insight into our meeting cadence needs.

**Comment by AramZS** [comment]
I think this is resolved. Any objections to closing it?
