### ISSUE TITLE
Agenda Request -  Call for Progress Report on Private Measurement

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#42]
## Agenda+: With work ongoing in the Private Measurement project it would be good to get a brief progress report and Q&A on the discussion thus far. 

There has been some very active discussion on the private measurement space. With that in mind I'd like to take some time on the Agenda to talk through the discussion thus far and give participants an update. We will need someone to lead that discussion who will be designated here. 

### Links

https://github.com/patcg/private-measurement

**Comment by AramZS** [comment]
I see progress on answering some of the major questions in the space as well as some proposals to move forward on progress. 

@betuldurak @erik-anderson @eriktaubeneck @bmayd @martinthomson @dmarti @benjaminsavage @darobin I see you all participating in this space by orchestrating discussion around ideas, features, and concepts around tests to prove out particular concepts. Would any of you like to take a chunk of this time to review any significant discussion or useful feedback going into this conversation?

**Comment by martinthomson** [comment]
See #44.

**Comment by betuldurak** [comment]
It would be valuable to hear from @tgeoghegan and others about "other purposes" (within the scope of standardization as well). What aggregates are meaningful, scalability to larger bits for counts/others, communication/computation efficiency of Prio/Poplar. My hope is to get more understanding on test vectors to consider which was intended to do in
#https://github.com/patcg/private-measurement/issues/7

**Comment by AramZS** [comment]
@betuldurak We're going to bring in @tgeoghegan for their own time slot via #44 . Let me know where there might be other stuff we want to discuss in this slot.

**Comment by betuldurak** [comment]
Thanks @AramZS I have these questions for the guest and whoever wants to participate to discuss. The time of his slot may be enough depending on other questions he will get, hard to tell. Judging from no response to #https://github.com/patcg/private-measurement/issues/7, my understanding was that there is not enough interest (just yet) on discussing these questions in a separate slot.

**Comment by AramZS** [comment]
Thanks to all who spoke!
