### ISSUE TITLE
Agenda Request -  Operational experience with MPC

### ISSUE THREAD

**Issue by martinthomson** [patcg/meetings#44]
## Agenda+: ISRG experience with running an MPC

@tgeoghegan is willing to speak on the ISRG experience with running a PPM system if we can fix a time.  I anticipate that we might have some questions about how they run their part of the Prio system for exposure notifications and other purposes.  Tim is also involved in the IETF standardization of Prio and Poplar.

### Links

https://divviup.org/

**Comment by tgeoghegan** [comment]
Some more useful reference material:

[ENPA whitepaper](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ENPA_White_Paper.pdf)
[`prio-server`, ISRG's ENPA aggregator implementation](https://github.com/divviup/prio-server)

**Comment by martinthomson** [comment]
Note: knowing when this is expected to be scheduled will help Tim out as I don't think that he is able to commit to 6 hours of meetings.

**Comment by AramZS** [comment]
@martinthomson If there are no objections I think we can put him starting at 50m into Day 2 (9:50am ET), right before #42's time slot? If he could get in a little earlier than that, like at least at the 30m mark that would be useful. How long do you think the presentation should be? 20m + 10m of Q&A?

**Comment by AramZS** [comment]
@tgeoghegan Does the above timing work for you? ^

**Comment by tgeoghegan** [comment]
I won't have any time to prepare a presentation, but I'm happy to join a call and informally answer any questions the group has. 9:50 AM ET on Thursday April 7 is fine.

**Comment by AramZS** [comment]
Ok, I think we don't need a whole 30m slot for that then, I'll put aside 15m on the agenda for Q&A on this. Thanks @tgeoghegan !

**Comment by AramZS** [comment]
Thanks @tgeoghegan for your excellent work handling these questions and pushing forward our knowledge on this topic.
