### ISSUE TITLE
Call for Scribes - 2022-04 Meeting

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#46]
## Looking for participants who will volunteer to take active notes

Please comment on this issue if you are willing to scribe notes actively during the meeting. If you are only able to scribe one of the two days, please note that. If possible it would be nice to switch scribes per-hour.

Thanks!

**Comment by npdoty** [comment]
I can scribe for an hour, either day. (I'll scribe better if it's not the first hour of the meeting so I'll have had my coffee first.)

**Comment by wseltzer** [comment]
I can take a slot Tuesday

**Comment by seanturner** [comment]
Notes can go here:
https://docs.google.com/document/d/1zsFNB-1tNUbSP6V2xpCDhiaPUN3B_lT_qn0OnzLvtYM/edit

**Comment by schoppmp** [comment]
I can scribe for an hour on Thursday.

**Comment by AramZS** [comment]
Thanks to all scribes!
