### ISSUE TITLE
Confirm Interest in TPAC F2F

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#53]
Setting aside time at the end of day 2 to talk through the logistics of setting a time TPAC-based Face to Face up.

**Comment by seanturner** [comment]
As discussed at the 17/19 May meeting, please indicate in this issue whether you would participate in-person at this CG's session at the [TPAC 2022](https://www.w3.org/blog/news/archives/9503) hybrid meeting scheduled for 12-16 September 2022 in Vancouver, Canada. We understand it might be hard for some to anticipate travel this far out due to world events, but some input is required for the W3C meeting planners. We need to submit the in-person head count data by 31 May 2022, so please let us know by 30 May 2022.

Thanks!

**Comment by seanturner** [comment]
I would attend in-person.

**Comment by csharrison** [comment]
I also intend to attend in person.

**Comment by bedfordsean** [comment]
I'll be there in person as well

**Comment by alextcone** [comment]
I plan to attend in person.

**Comment by johnwilander** [comment]
I intend to attend, so called ittend.

**Comment by schoppmp** [comment]
I'd also like to attend in person.

**Comment by jaylett-annalect** [comment]
I also plan to attend in person.

**Comment by bjd326** [comment]
Myself and another from Tech Lab plan to be there.

**Comment by michaelkleber** [comment]
I plan to attend in person

**Comment by MosheLehrer** [comment]
I'm trying to figure out logistics, but tentatively plan on attending.

**Comment by ekr** [comment]
I tentatively plan to attend.

**Comment by ssanjay-saran** [comment]
Tentatively plan to attend.

**Comment by jonasz** [comment]
I tentatively plan do attend in person.

**Comment by donivatamazondotcom** [comment]
Just getting up to speed on the happenings in the various W3C groups and it would be great to meet folks f2f. I'll plan to attend in person.

**Comment by cwilso** [comment]
I would plan to attend.

**Comment by gjlondon** [comment]
I tentatively plan to attend

**Comment by seanturner** [comment]
Hi! Reminder to provide your tentative plans for TPAC 2022 WRT whether you plan to attend in-person.
Thanks!

**Comment by martinthomson** [comment]
Planning to attend also, with usual caveats.

**Comment by erik-anderson** [comment]
I plan to attend.

**Comment by lbdvt** [comment]
Tentatively plan to attend.

**Comment by jpfeiffe** [comment]
I plan to attend, with two others.

**Comment by stumakha** [comment]
Tentatively plan to attend.

**Comment by seanturner** [comment]
Thanks to all those that participated. I am going to go ahead and submit the info that I have to the W3c.

**Comment by bmayd** [comment]
Sorry for the late reply, I may be attending as well.

**Comment by richajaindce** [comment]
I plan to attend as well, apologies for the late response!

**Comment by AramZS** [comment]
@seanturner I believe we have a time for TPAC upcoming? If so we'll aim to discuss it in this upcoming meeting.

**Comment by seanturner** [comment]
As noted on the 6/21 telecon, we are currently scheduled for Tuesday (9/13). Additionally, I was made aware that CG's are usually limited to 20 people; we had about 30 indicate they would be present. As we might be a WG by then we will see how this turns out.
