### ISSUE TITLE
Agenda Set - Request for Scribes

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#54]
Hello all, 

The agenda is now set for our meeting this week. Please feel free to open up PRs against it to add more information. 

https://github.com/patcg/meetings/tree/main/2022/05/17-telecon

I'd also ask that we could get scribes to volunteer in advance if possible. 

Thanks!

**Comment by michaelkleber** [comment]
I'll offer to scribe for "Deep dive on measurement use cases and requirements led by @csharrison" on Day 1.

**Comment by eriktaubeneck** [comment]
Happy to scribe for "Keeping good ads off bad sites" later today.

**Comment by seanturner** [comment]
Please volunteer to scribe for Thursday's session.

Thanks!

**Comment by csharrison** [comment]
I volunteer to scribe for the "Collective Governance of Infrastructure" topic

**Comment by seanturner** [comment]
@csharrison thanks!

Any other takers?

**Comment by eriktaubeneck** [comment]
Happy to scribe for any of the sessions other than "Aggregate Measurement Threat Model" (which I am leading.)

**Comment by seanturner** [comment]
Thanks for those that scribed!
