### ISSUE TITLE
June 2022 Meeting

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#57]
[Please fill out this poll to indicate your availability.](https://doodle.com/meeting/participate/id/erkALZKa) We would like to make the decision by May 31st so please indicate your preferences by then.

Aram and I would like to schedule the next patcg meeting for either the 3rd Tuesday/Thursday (21/23) or the 4th Tuesday/Thursday (28/30) of June; sometime zones will be 20/22 and 27/29. We will again have the two 3 hour sessions. As agreed, we are going to rotate the time of day around so that at some point everybody will need to be up early/late. This time we are proposing [0800 CEST / 0700 BST / 0600 UTC / 0200 EDT / 2300 PDT (previous day) / 1400 Singapore / 1600 AEST](https://everytimezone.com/?t=62afb880,708). An early set of apologies to those who have bad start times.

**Comment by seanturner** [comment]
Hi! Gentle reminder to please fill the doodle poll for the June meeting.
Thanks!

**Comment by seanturner** [comment]
Hi! Another gentle reminder to provide your input. We hope to nail down the time this week.
Cheers!

**Comment by eriktaubeneck** [comment]
@seanturner thanks for the post-long weekend reminder!

**Comment by seanturner** [comment]
It looks like we have to best chance of getting the most people on 21 & 23 June so I will begin the process to get that scheduled.

Thanks,
spt

**Comment by seanturner** [comment]
@piwanczak It is a two day event. 21st and 23rd (some variation on timezone). The zoom link for both days is the same. Also see [link](https://github.com/patcg/meetings/blob/main/2022/06/21-telecon/README.md).
