### ISSUE TITLE
Agenda Request -  Buy-side use cases + requirements deep dive.

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#59]
## Agenda+: Hear from buy-side participants at the advertiser and agency level

With help from participants, including @alextcone & @jaylett-annalect, we hope to invite guests to discuss the ad buyer perspective on the future of more private ad tech in more detail. 

### Links

This should follow up on the conversation we had around https://github.com/patcg/meetings/issues/51

**Comment by alextcone** [comment]
I'm unfortunately not going to be able to coax my expert into a 2-5 AM meeting :/

**Comment by AramZS** [comment]
@alextcone Yes, sorry if it wasn't clear, I marked this as Agenda+next to indicate that it won't be in this month's session, but next month's

**Comment by rmirisola** [comment]
If you are interested I can try to bring in some advertiser / advertiser representatives from WFA/ANA/ISBA

**Comment by jaylett-annalect** [comment]
The proposed time for the August meeting isn't going to work for my London-based team colleague that I'm lining up to present and answer questions for this. My assumption from @AramZS's comment was that we'd aim for a time slot that worked for both Europe & the US. (Additionally, both myself and my colleague are away the second week, but that's moot given the time slot.) Given TPAC in September, are we looking at October for doing this such that we can bring in European buy-side folks who aren't members of the group?

**Comment by seanturner** [comment]
Based on our meeting cadence, yes there should be a meeting in October.

**Comment by AramZS** [comment]
@jaylett-annalect, @rmirisola  and @alextcone Just confirming that the October meeting time would be a good time for you all to bring in representatives from your orgs to speak to use cases and requirements? I think, considering the number of folks that sound like they want to be involved, we could dedicate a whole day to it?

**Comment by jaylett-annalect** [comment]
@AramZS that should work for us.

**Comment by alextcone** [comment]
@AramZS - I can work on a few folks who might be interested. I just read this today from a practitioner who is in my orbit.

https://newdigitalage.co/programmatic/a-day-in-the-life-of-a-programmatic-trading-advisor/

@drpaulfarrow, do you think Stefan would be game to talk to the PATCG about common measurement/attribution practices and challenges both now and foreseen (with reduced x-site/app IDs)?

**Comment by AramZS** [comment]
@alextcone @jaylett-annalect @drpaulfarrow Still up to bringing folks to the October meeting? We have the 25th and the 27th both at 9am to 12pm where we can bring people in. I'd like to bring folks in for one whole day if possible and we can lock it into the Agenda on one of those two days?

**Comment by jaylett-annalect** [comment]
@AramZS my original choice is unfortunately not available, but I am talking internally to see who else can join. We have been working on a short narrative presentation that will explain how we think of measurement and how it fits into advertising planning and delivery – but I would expect the bulk of the session to be Q&A even after a few presentations.

**Comment by alextcone** [comment]
@AramZS I'm acknowledging this ping and pinging my friend Laura.

**Comment by jaylett-annalect** [comment]
27th would be preferable from our end I think, although I'm still waiting to confirm our measurement expert. Also planning to bring along one of our adtech folks from the UK team.

**Comment by jaylett-annalect** [comment]
@AramZS there was discussion in the August telcon of trying to pull questions together, did anything come of that? Not a problem if not, but obviously anything to help people prepare would be useful.

**Comment by alextcone** [comment]
@AramZS apologies for making this difficult for you, but my contact, Laura, prefers October 25 to 27. She said she can make the 27th work if she has too.

Will watch for response to @jaylett-annalect's question re: questions.

**Comment by AramZS** [comment]
@jaylett-annalect I'll ping folks to see if they can submit questions to this thread. Let's put 1.5h on the 27th for your group and potentially @drpaulfarrow's contact as well. 

@alextcone If only the 25th works we could split the session. I guess part of the question would be if she'd like to be more part of a panel experience. I'd like to unify them into one session if possible?

**Comment by bmayd** [comment]
+1 on unifying so that presenters can identify where they are aligned in how they approach various use-cases or where and why their perspective differs. (At the risk of looking the proverbial gift-horse in the mouth.)

**Comment by alextcone** [comment]
@AramZS I think the 27th works for Laura. It just wasn't first choice, that's all.

**Comment by AramZS** [comment]
@alextcone Ok, let's set the 27th for buy-side folks.

**Comment by AramZS** [comment]
I'm going to break out a request for questions thread here - https://github.com/patcg/meetings/issues/80

How do we feel about 2h for this? We can go longer if needed but the measurement document sounds like it may need an extra hour on day 2.

**Comment by AramZS** [comment]
Hi @alextcone @jaylett-annalect @drpaulfarrow - just a reminder we're putting aside the first 2h of the 27th for your guests. Please let me know if you need additional info.

**Comment by drpaulfarrow** [comment]
Sorry, I am a bit confused by the ask. I haven't been able to make recent
sessions. Is the expectation that Stefan will come and present to the
group?

**Comment by AramZS** [comment]
Yes, if possible! @drpaulfarrow
