### ISSUE TITLE
Mechanism for Meeting Minutes

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#6]
At the kickoff meeting the patcg used [irc](https://github.com/patcg/meetings/tree/main/2021/10-tpac#minutes) as the tool for recording meeting minutes. It was chosen primarily because of chair familiarity with it as well W3C-related tooling to get the cleaned up minutes in the right place. At the end of that patcg meeting, there seemed to be support for using Google Docs instead at our next meeting. We are going to try that. The chairs will create a Google Doc and share the link during the session. Anyone with the link can then contribute to editing the files; it would be great if the scribes could use markdown formatting. After the meeting, the chairs will cleanup the minutes (and if not already in markdown convert them and include them in the meeting's GitHub repository which resides [here](https://github.com/patcg/meetings). Ultimately, the minutes will be sent to the list by the W3C GitHub notify bot (or the chairs).

**Comment by bslassey** [comment]
There are some tools to export markdown from gdocs, which might be easier for folks than manually typing in markdown. I'd be happy to do the conversion.

**Comment by eriktaubeneck** [comment]
I greatly appreciate that this feedback was heard, and that we're willing to give this a try. In my (limited) experience with the W3C, I've found it much easier to follow along and act as a scribe in the meetings that have operated in this way within a collaborative document.

I will volunteer myself now to help scribe in the meetings (though if they are going to be multi-hour, maybe not for the entire time... 😅). Also, as @bslassey points out, it may be easier to format directly in the doc, and convert to markdown after. I'm certainly also happy to help clean that up where it doesn't cleanly map via the tools.

**Comment by AramZS** [comment]
I think converting to markdown shouldn't be too much of an issue, there are a lot of tools for this, we'll find the one we like best, document it and use it. I am inclined towards a collaborative document considering the interest, but I am not surprised to find at least one (and therefore likely more than one) participant has Google Docs fire-walled. I think this means we should lean towards a different collaborative document writing tool.

**Comment by csharrison** [comment]
I convert Google Docs to markdown for the Attribution Reporting API meetings using [Docs to Markdown](https://github.com/evbacher/gd2md-html/wiki) and I basically have never needed to "touch-up" the result. It is a very easy process.

**Comment by eriktaubeneck** [comment]
> I am inclined towards a collaborative document considering the interest, but I am not surprised to find at least one (and therefore likely more than one) participant has Google Docs fire-walled. I think this means we should lean towards a different collaborative document writing tool.

While we should strive to make this as inclusive as possible, I'm not sure I would reach the same conclusion. Many other CGs operate with Google Docs without complaint, and if we want to consider something else, we should understand how common an issue this is, and if participants can find work arounds. I'd also be surprised if other options weren't also firewalled for that subset of people.

Ideally, we'd have a solution that supports the following functionality (in order of importance):
1. Collaborative editing that enables editing/fixing mistakes, multiple scribes to fill in missing works/ideas, and a dynamic queue (i.e. removing folks as they speak.)
2. Ability to add inline comments, to clarify points. Especially useful if it's possible to tag the speaker.
3. Able to handle a large number of participants without leading to fractured state / crashing docs.

My primary objection to IRC is that it doesn't handle (1) and (2) at all, and when I've participated as a scribe in other CGs, this functionality has been extremely important. Google Docs is, in my experience, best in class on (3) for collaborative docs. Given the excitement around this group, it seems like we should lean into the solution that's most likely to support a large number of participants.

**Comment by bmayd** [comment]
>Given the excitement around this group, it seems like we should lean into the solution that's most likely to support a large number of participants.
I agree and think we should prioritize good, easily captured, corrected and reviewed minutes.

**Comment by AramZS** [comment]
We do have at least one participant calling out Google Docs as being blocked in their company and I wouldn't be surprised to find other participants have that issue. I think that while it has its problems use of [Cryptpad](https://cryptpad.w3ctag.org) has been established as a middle-ground tool in other very active CGs and that seems like the logical fallback unless anyone here has a strong feeling towards another solution Since this solution is hosted by W3C tag I suspect that firewall issues are not as likely a concern? This issue is now reaching all participants through email, so if there are other people with issues accessing either the instance of cryptpad or Google Docs it would be helpful to have them speak up as to any accessibility issues or workarounds that might be possible.

**Comment by lmarkou1** [comment]
I can workaround google docs. I just send to a different device. no need to find a workaround if I'm the only one.

**Comment by AramZS** [comment]
The only on the record objection has an alternative way to access Google Docs so, for the foreseeable future let's make a note that we intend to use Google Docs for minute-taking.
