### ISSUE TITLE
TPAC 2022

### ISSUE THREAD

**Issue by lbdvt** [patcg/meetings#67]
TPAC registration is now open. https://github.com/patcg/meetings/issues/53#issuecomment-1161360175 suggests that there might be more people interested to attend the PATCG session in-person than the room can seat. 

Before planning trips, could you please share if it turns out to be the case, how would that be handled?

**Comment by jaylett-annalect** [comment]
Further, I tried to register over the weekend and didn't have permissions to start the registration flow. Not sure if this is a problem specific to me, or if CG members not attached to W3 member orgs will have problems (or if there's something I'm doing wrong).

**Comment by AramZS** [comment]
@jaylett-annalect Hey, I don't think it should, just verifying: you did sign up for the Community Group?

**Comment by seanturner** [comment]
> TPAC registration is now open. [#53 (comment)](https://github.com/patcg/meetings/issues/53#issuecomment-1161360175) suggests that there might be more people interested to attend the PATCG session in-person than the room can seat.
> 
> Before planning trips, could you please share if it turns out to be the case, how would that be handled?

Going to see if I can't find out more about the room's size.

**Comment by jaylett-annalect** [comment]
@AramZS I'm a member of the community group (As in signed up properly, executed the CLA), and I was trying to sign up using the link on this page: https://www.w3.org/register/tpac2022

**Comment by seanturner** [comment]
@lbdvt What I have heard back is that the room size is not known, but in practice, the room size shouldn't be an issue.

**Comment by AramZS** [comment]
> @AramZS I'm a member of the community group (As in signed up properly, executed the CLA), and I was trying to sign up using the link on this page: https://www.w3.org/register/tpac2022

@jaylett-annalect Are you seeing yourself logged in, with your name on the upper right hand corner?
