### ISSUE TITLE
Agenda Request -  Aggregate Measurement Threat Model Status Report

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#69]
## Agenda+: Aggregate Measurement Threat Model Status Report

[In May](https://github.com/patcg/meetings/issues/50) @eriktaubeneck, @martinthomson, @csharrison and @chris-wood volunteered to draft a threat model document. Has this document yet reached a state ready for a progress report? If so, we'd like to discuss it and maybe get an early draft in the documents repo? 

### Links

Slides at https://github.com/patcg/meetings/blob/main/2022/05/17-telecon/Aggregate%20Measurement%20Threat%20Model%20-%20PATCG%20Issue%20%2350.pdf

**Comment by eriktaubeneck** [comment]
We are aiming to have a draft out in advance of the next meeting, and I'm happy to lead this agenda item for the next meeting.

**Comment by AramZS** [comment]
@eriktaubeneck Great! How much time do you think you'll need? At this time I'm thinking about 1h?

**Comment by eriktaubeneck** [comment]
@AramZS 1hr seems good, I'm hoping that it will be mostly discussion. I'll open a PR against the docs repo soon!

**Comment by eriktaubeneck** [comment]
FYI, I opened a PR for this today. Sorry to be so last minute, but I just returned from vacation 🙂
