### ISSUE TITLE
Chartering the Working Group

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#7]
One of our top of mind tasks to kick off should be chartering the Privacy Advertising Technology Working Group (as stated in the charter). In our first meeting we should set this task, editors, and be clear about paths to involvement and feedback from members who wish to be involved.

**Comment by AramZS** [comment]
Hey all, we're looking for volunteers to work in the initial editorial group for the Private Advertising Working Group charter, if you aren't on this group, there's no pressure to join in order to be involved as it will loop back around for the larger group to review. The initial target deliverable will be an outline of the charter for discussion and later this group would be asked to review feedback and continue forward on building out the charter. A diverse set of participants and constituencies would be appreciated here. It would be helpful for interested participants to self-nominate in advance of the meeting.

**Comment by ekr** [comment]
I am volunteering...

**Comment by alextcone** [comment]
I volunteer

**Comment by bslassey** [comment]
I will also volunteer to work on this

**Comment by lukwlodarczyk** [comment]
Please let me know what i can do to help

**Comment by wseltzer** [comment]
I'm happy to offer W3C team support. W3C provides a [charter template](https://w3c.github.io/charter-drafts/charter-template.html) in [github](https://github.com/w3c/charter-drafts) as a starting point for the elements required by Process.

**Comment by eriktaubeneck** [comment]
I volunteer (async on the document, I won't be able to attend the upcoming meeting.)

**Comment by Simon-J-Harris** [comment]
Would love to help where I can!

**Comment by darobin** [comment]
Ooooh, charters are so much fun — count me in!

**Comment by benjaminsavage** [comment]
I volunteer as well.

**Comment by AramZS** [comment]
I believe we established @ekr to take first cut at this as a Google doc with feedback coming in from the group of editors volunteered here with the aim of moving towards a stand along repo in the near future.

**Comment by ekr** [comment]
OK, here is the gdoc:
https://docs.google.com/document/d/13H-4If0ri2KDzonib0g9ZL3Oh2X3qo6DRiayYP8vsQE/edit?usp=sharing

Let's try to iterate on this over the next week or two and then we can stuff it in a PR or a Repo or whatever.

**Comment by ekr** [comment]
Last call for comments. Will migrate to a PR next week.

**Comment by seanturner** [comment]
@ekr pretty sure you were going to do this, but please submit the PR to [admin repo](https://github.com/patcg/admin/pulls).

**Comment by jwrosewell** [comment]
I've made a number of suggestions to ensure that the input data to any solution is not restricted only to web browser implementers.

**Comment by ekr** [comment]
Thanks. @jwrosewell I can transcribe your comments in the gdoc into Github so you don't have to do it twice, or you can submit PRs, if you prefer.

**Comment by AramZS** [comment]
Considering the current set of issues and PRs around the Working Group charter, I would like to review the charter and close as many issues as possible in the 40m I have for this topic at the end of Day 1. If you have not reviewed the proposed charter and issues, please do so in advance of the meeting.

**Comment by seanturner** [comment]
Since the WG is now chartered. I am going to go ahead and close this issue.
