### ISSUE TITLE
Agenda Request -  IPA Status Update

### ISSUE THREAD

**Issue by eriktaubeneck** [patcg/meetings#70]
## Agenda+: IPA Status Update

@martinthomson, @benjaminsavage, @bmcase, Daniel Masny, and myself are planning to publish an update on IPA in the coming week. We'd like to set aside some time at the next meeting to share our progress.

### Links

This is a follow up to our [initial proposal](https://github.com/patcg/private-measurement/issues/9). I will add a link to the update here once it's published.

**Comment by AramZS** [comment]
@eriktaubeneck Can do! How much time do you need to present? And I'd think at least 30m for Q&A.

**Comment by eriktaubeneck** [comment]
I think 90 min (if we have room for it) will suffice (including 30 min of that for Q&A.) Thanks!

**Comment by eriktaubeneck** [comment]
Here's [a link to our latest draft](https://github.com/eriktaubeneck/ipa-draft/blob/main/IPA-End-to-End.md) of the protocol. We'll present an overview during the session (though likely won't get into all the technical details.) We will be prepared to answer questions about any part of the proposal, and also encourage people to open issues directly on the newly created [IPA Draft repo](https://github.com/eriktaubeneck/ipa-draft).

**Comment by eriktaubeneck** [comment]
Updated links (original comment included the wrong repo): [latest draft](https://github.com/patcg-individual-drafts/ipa/blob/main/IPA-End-to-End.md) and [IPA Draft repo](https://github.com/patcg-individual-drafts/ipa/blob/main/IPA-End-to-End.md)

**Comment by benjaminsavage** [comment]
Hi @alexWhitworth - I think you've misunderstood the proposal. That is not what the "helper party network" refers to.

It refers to a group of three distinct companies, each of whom operate a server which would run an MPC protocol that conformed to the specification. 

These entities are *minimally trusted*. That is, they are never entrusted with raw user data. They only ever see "secret shared" data, which cannot possibly be converted back to raw user-data without collusion between the helpers. As such, the *only* thing we need to trust about these helpers is that there is AT MOST one malicious one. So long as there is at most one malicious helper, it is not possible for user privacy to be violated.

As for how these three entities would be chosen, it would be up to the browser or mobile-OS vendor to select a group of companies that *they* trust to not intentionally collude amongst one another to violate user privacy.

**Comment by eriktaubeneck** [comment]
Thanks for the question @alexWhitworth. The technical proposal is intentionally abstract about the _helper parties networks_; for the protocol, we have to assume that such a group of parties that will be trusted by browser vendors to have this non-collusion property will exist. 

What you are getting at is actually more of a policy question (and less of a technical one.) Who will run these? My personal opinion is that we'll likely see a small handful of such networks emerge, and my hope is that some of them will be trusted to be non-colluding. I imagine these will consist of entities like the [Internet Security Research Group (ISRG)](https://www.abetterinternet.org/) who is working on a service similar to this, [DivviUp](https://divviup.org/). 

As for publishers and advertisers participating in the helper party networks: this seems less likely. In the past, I've heard the view that we should assume in our threat model that publishers and advertisers are colluding. So it's unlikely this becomes advertiser + publisher + trusted 3rd party, but rather networks of semi-trusted 3rd parties.

As for the need for MPC (vs a "data clean room".) This is more relevant to the threat model discussion. which there is a [draft in the Docs and Reports repo](https://github.com/patcg/docs-and-reports). But in general, even if we have a helper party network made up of 3 (more abstractly, more than 1) parties all very much like the ISRG, the goal is to not have to trust any single party. In terms of the threat model, there shouldn't be any single entity who could collude with a publisher, advertiser, or report collector, and reveal the data, hence the need for an MPC.

**Comment by benjaminsavage** [comment]
Today at the PAT-CG meeting Chris Wood mentioned that Cloudflare would also be interested in operating open-source MPC protocols like DivviUp and potentially IPA. So that's another specific answer to your question @alexWhitworth =).

**Comment by martinthomson** [comment]
cc @chris-wood who can probably qualify that more precisely.

**Comment by alextcone** [comment]
It’s hard for me to believe that any public cloud provider would turn down digital advertising compute. In fact I would assume all of them are salivating watching this work and the related work at IETF. I think the question is, do we intend to look to the cloud providers themselves for being responsible and responsive for issues with their implementation? The Divviup example shows us that at least some browsers would trust a software provider built on top of the public cloud provider. I presume this is in part because Mozilla is on the board of ISRG. It’s noteworthy that OVHCloud and Amazon are also on the board. Cisco as well. Ultimately, I realize it’s up to user agents to decide who to encrypt toward, but I cannot imagine there are cloud companies or honestly anyone else who will say “not interested.”

**Comment by eriktaubeneck** [comment]
Folks, I opened [What parties will participate in helper party networks?](https://github.com/patcg/private-measurement/issues/19) in the private-measurement repo to continue this conversation. I did my best to summarize points above, but please feel free to add more detail and continue the conversation there.
