### ISSUE TITLE
Agenda Request - Private Measurement Document

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#78]
## Agenda+: Private Measurement Document report from editorial team

I want one of our days in the October meeting to be dedicated to moving through the current state of the private measurement document, hearing from editors, and making sure the larger group can contribute what is needed to help move forward. 

## Time

I leave this up to the editorial group, but I suspect a full meeting time of 3h will be required. It would be good to break that time down into a more nuanced set of agenda items however. 

### Links

Editor list: https://github.com/patcg/meetings/tree/main/2022/09/13-tpac#volunteers-aka-willing-victims

Requesting more detail for how they would like this to go from editors whose GitHub names I have on hand:

@csharrison 
@eriktaubeneck 
@martinthomson 
@marianapr

**Comment by csharrison** [comment]
Here is a draft of the [document](https://docs.google.com/document/d/1_mq2e_Yuxwh1664S3Ep_yVgOECHqyF27Qiev6UrmQFk/edit#heading=h.koi0qr7e88te) we've been iterating on.

In general, it is split out into 3 sections:
1. Important design dimensions
2. Key use-cases that differ on the dimensions
3. Layering ideas to support different vendors making different decisions in a (somewhat) interoperable way.

I honestly think these topics could take > 3hrs. Here's a strawman set of discussion points:

Discussion on (1) can focus on answering questions like:
- Where do we see easy alignment vs. difficult alignment? I don't know if everyone will be prepared with hard decisions as 'red lines' but we can at least flag concerns (and maybe some dimensions will have no concerns from anyone)
- Are there missing dimensions?

For (2), beyond information sharing we should dive into whether there are any key at-risk use-case or feature that we ought to highlight.

For (3) we'd likely want to discuss meta alignment on layering in general, including guiding principles, as well as the specific listed items for concretely how this could be done.

**Comment by AramZS** [comment]
I'm looking at 3hrs on day one and an additional hour after the buy side convo on day two. And if the buy-side convo goes short, you'll get the extra time.
