### ISSUE TITLE
Take up IPA proposal

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#8]
The Proposal repo holds [issue 2 which intends to cover private attribution processes](https://github.com/patcg/proposals/issues/2) to "addresses the aggregate attribution measurement use case". We should take up this proposal, decide next steps and move forward with it as determined by the group.

**Comment by martinthomson** [comment]
Hi @AramZS, perhaps the plan I suggested in https://github.com/patcg/meetings/issues/9#issuecomment-1012587768 is a neater approach than considering just one of the many proposals - at this time.  I don't think we need to do anything more at this stage than ask what functionality is being considered (perhaps attribution, maybe reach and frequency) and the way in which we might approach providing that functionality.
