### ISSUE TITLE
Agenda Request -  TEEs and MPC in the Threat Model

### ISSUE THREAD

**Issue by eriktaubeneck** [patcg/meetings#81]
## Agenda+: Private Computation Abstraction for TEEs and MPC in the Threat Model

**Time**: 30-45 min

I recently [opened a PR on the docs-and-reports](https://github.com/patcg/docs-and-reports/pull/14) that attempts to create a higher level of abstraction for *private computation*, with both TEEs and MPC as ways in which private computation can be achieved within the assumptions of the threat model. The main idea is to shift this decision (along with two other related decisions, the privacy budget and aggregation threshold) onto the implementor, rather than requiring consensus in the standard.

I'd like to spend some time in our upcoming meeting to present this idea and get some initial feedback. (If you'd like to engage directly on the topic, please [comment on the PR](https://github.com/patcg/docs-and-reports/pull/14) instead of this issue.)

**Comment by AramZS** [comment]
@eriktaubeneck Do you feel this needs to be for the upcoming meeting? We already have a pretty full plate so if you do, we'll lock it in at 30m if that's ok?

**Comment by eriktaubeneck** [comment]
My apologies, I missed #79. At quick glance, I only say #59 and #78, so thought maybe there would be room for another short one.

It's not particularly important to make any decision, but it might be helpful for #78, if only to avoid focus on this particular dimension in that conversation. The only other consideration is that I personally am likely to be on parental leave at our next meeting, so that may push it out further.

I can certainly fit it into a 30 min slot if you can find it.

**Comment by csharrison** [comment]
This document fits into one of the slots in #78 (layering). I would be happy to focus that section of #78 on this document given that it is a concrete idea.

**Comment by eriktaubeneck** [comment]
@csharrison that makes sense. Are you OK with me putting slides together and leading that part of the conversation? 

(cc @AramZS, no need for a stand alone slot in the agenda.)
