### ISSUE TITLE
Request for an Ad-Hoc Meeting On:

### ISSUE THREAD

**Issue by Likeadiamondsajmon** [patcg/meetings#86]
## Ad-Hoc+ What do you want to meet on?

Add a title above that makes clear the purpose and scope of this meeting. What do you want to discuss and to what end? When writing this section include links to specific issues or entity's in the proposals repository this meeting intends to discuss and goals you have for the outcome.

## Timing

Is this a one-off meeting to handle a specific hot issue? Do you want to establish a reoccurring meeting to work on specifics of a proposal or report? Please make this clear to participants who may want to get involved. 

## Scheduling

When do you want this meeting to occur? Time and day suggestions are very welcome here, as are a potential mechanism for polling participants. If this is a reoccurring meeting, please include the frequency (weekly, monthly, etc...) or a choice of frequencies. 

## Links 

If your agenda item wishes to discuss some external document, spec, or proposal, you should include links to that document here. Please do not assume a reader has read any existing document. Always link.

**Comment by AramZS** [comment]
This appears to be created in error?
