### ISSUE TITLE
F2F Meeting Cadence

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#88]
Hi! Please fill out this [gForm](https://forms.gle/942U6rh7bNbRPWCVA) to let the chairs know how often and when you think the Private Advertising Technology CG/WG should meet F2F. If you are unable to use this form, please send an email to [Sean Turner](mailto:sean@sn3rd.com?subject=[patcg]%20F2F%20Meeting%20Cadence) indicating:

How Many Times Per Year : [never, one, two, three, four, other]

When: [every other meeting, every 2nd meeting, January, …, December, other]

**NOTE** I am not trying to collect your email addresses.

**Comment by seanturner** [comment]
BTW as we have no real budget to reserve meeting space, we have to rely on a host. And, we do have some requirements that makes scheduling a little challenging: 50+ attendees, A/V capable, and no NDA.  If you have access to a meeting space that can support us, please let me know via [email](mailto:sean@sn3rd.com?subject=[patcg]%20Potential%20F2F%20Meeting%20Space).

**Comment by seanturner** [comment]
The other thing, I actually didn't consider but you might have when picking two, is that we will definitely schedule time at TPAC.

**Comment by jaylett-annalect** [comment]
Can I express a preference for F2F meetings, when they happen, to attempt to avoid starting on a Monday? This would facilitate working-time travel for people who need it. (Not really about cadence, but also not completely unrelated and feels better than a separate issue.)

**Comment by bmayd** [comment]
Can we clarify that the F2F meetings are in addition to TPAC and provide some guidance around when TPAC is happening so folks can take it into account in their responses regarding timing?

**Comment by seanturner** [comment]
We currently have 6 responses.

TPAC is usually sometime in September or October; assuming it happens this year, and I do not know why there would not be one this year (see [wiki](https://www.w3.org/wiki/TPAC)).

I would like for this to include TPAC, e.g., you picked two - then one of those would include TPAC.

**Comment by samuelweiler** [comment]
> TPAC is usually sometime in September or October; assuming it happens this year, and I do not know why there would not be one this year (see [wiki](https://www.w3.org/wiki/TPAC)).

See https://github.com/patcg/meetings/issues/89#issuecomment-1380623235

**Comment by seanturner** [comment]
The general sense we have is that there should be at least two and maybe three in person meetings. We just had one (in Feb) and we are going to ask for time at TPAC (more than one hour, but how much more depends). There seemed to be general agreement that if were to do another F2F we'd be targeting the June meeting time frame.

As far as scheduling at TPAC, I have heard that if folks are willing to stay Friday afternoon that we can get a large block of time, e.g., 4 hours. If not, then we are likely to not get more than 2 hours and we are likely to only get 2 hours if we are chartered as a WG.

**Comment by seanturner** [comment]
Unless there's any objections I feel like we can close this issue. We've kind of settled on 3 F2F meetings: 2 we plan on our own and one is at TPAC. Obviously, if we can't find a host far enough in advance of the meeting we will fall back to virtual.  And, if we suddenly find there's a need to meet more frequently we can always reopen this issue.

Shortly after TPAC (in September), Aram & I will open another issue to discuss plans for our 2024 F2F meetings.
