### ISSUE TITLE
Review baseline requirements for Private Measurement from participants 

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#91]
## Agenda+: What can we all agree upon in regards to private measurement? 

In advance of our upcoming meetings, we'd like to understand the baselines for particular design dimensions that browser vendors and participants would find acceptable, these issues are intended to describe particular dimensions [building off the document editors' work](https://github.com/patcg/docs-and-reports/blob/main/design-dimensions/README.md) and collect feedback from organizational participants to determine if, in a private measurement specification, they **could** accept this dimension. Answering no would mean you find such a feature totally unacceptable. Please also note if you consider such a feature to be *required*.

Optionally, but if possible, it would also be useful to know if they would prefer to accept this dimension.

Please respond in-thread, with yes or no answers to these questions. Especially if the answer to the question is no.

This is needed to facilitate a smooth meeting in the upcoming month. 

1. An API using an off-device private computation configuration is sufficient to ensure privacy of the output
2. The API requires requires in-browser as the primary site of operations to compute the output
3. Differential privacy used as a technique to assure privacy 
4. Information theoretic (e.g. entropy) used as a technique to assure privacy 
5. k-anonymity used as a technique to assure privacy
6. Data join / attribution occurs on-device 
7. Data join / attribution occurs off-device (on a private computation configuration)
8. Budgeting of data applied on a private computation configuration
9. Budgeting of data applied on the device 
10. Attribution across multiple channels / ad-tech
11. Scope of Privacy Budget includes time epoch 
12. Scope of Privacy Budget includes site domain 
13. Scope of Privacy Budget includes campaign
14. User data is limited by a privacy budget, with the amount of properties about a user further limited if the TLD delegates to a measurement provider outside of the TLD
15. Attribution can be done across devices
16. Attribution can be done across applications on the same device 
17. Can TEE be used as a private computation configuration?
18. Can MPC be used as a private computation configuration?
19. Can server-based data joining be handled by an MPC process? (If you require a specific number of parties, let us know) 
20. Can multiple third parties measure the same event with no restrictions? 
21. Can multiple third parties measure the same event with restrictions?
22. Can third parties invoke the measurement API? 
23. Can measure clicks 
24. Can measure views
25. Can measure predicted ghost ads, an opportunity when a user is eligible to be shown an ad but, due to a choice made by an advertiser-authorized system in order to measure that user as in a test or control group for testing, may have withdrawn or replaced the ad from being shown. 
26. Can connect interaction events (like generated a purchase or a form fill) on a landing site in connection to ad events, associating these ad events with desired outcomes on ad-defined target/landing sites
27. Can track events within the body of an ad beyond converting clicks and views, so long as those events are predefined by the ad's internal code (like a scroll event or video play)
28. A time delay is enforced before the report is emitted 
29. Some level of preregistration to participate with a browser vendor. 

If there are particular use cases you wish to support, [you may want to check the document to understand their requirements](https://github.com/patcg/docs-and-reports/blob/main/design-dimensions/README.md#key-use-cases-that-differ).

**Comment by eriktaubeneck** [comment]
Small nit: I think the term "trusted server" is a bit overloaded here, and is often thought of as a single trusted server (which I think we have general consensus is not acceptable.) In questions 17/18 we say "private computation configuration", and it might help to align that language elsewhere.

**Comment by bmayd** [comment]
@AramZS I'm not clear what is meant by "organizational participants", can you clarify?

**Comment by AramZS** [comment]
> Small nit: I think the term "trusted server" is a bit overloaded here, and is often thought of as a single trusted server (which I think we have general consensus is not acceptable.) In questions 17/18 we say "private computation configuration", and it might help to align that language elsewhere.

I've adjusted, let me know if it makes more sense here @eriktaubeneck

**Comment by csharrison** [comment]
Hey @AramZS , can you clarify a few points for me?

- **Scope of Privacy Budget is limited by delegation to another provider**. What does this mean exactly?
- **Can measure interaction events that do not 'convert' (send the user to another domain). This could include general interactions (mouse over, non-converting click, scroll event) or specific defined interactions like 'started a form fill' or 'played the in-ad game'.** It isn't clear what use-case this is describing. Are we talking about measuring "first-party only" information i.e. non-cross-site data?

**Comment by AramZS** [comment]
I've tried to pull as is from the preexisting document text, but if I've malformed here, let me know. Is this clearer phrasing on those two points @csharrison ? 

I can change `Scope of Privacy Budget is limited by delegation to another provider.` to `User data is limited by a privacy budget, with the amount of properties about a user further limited if the TLD delegates to a measurement provider outside of the TLD`

For the 2nd one, I think it may make more sense to split it. `Can measure interaction events that do not 'convert' (send the user to another domain). This could include general interactions (mouse over, non-converting click, scroll event) or specific defined interactions like 'started a form fill' or 'played the in-ad game'.` ->  

- `Can connect interaction events (like generated a purchase or a form fill) on a landing site in connection to ad events, associating these ad events with desired outcomes on ad-defined target/landing sites` 
- `Can track events within the body of an ad beyond converting clicks and views, so long as those events are predefined by the ad's internal code (like a scroll event or video play)` 

Do these changes make more sense?

**Comment by csharrison** [comment]
For the first one, do you mean like if `advertiser.com` delegates all their measurement to `3p.com`, they are disadvantaged because they will receive less overall budget than if they never delegated? If so, that rewording makes sense to me.

The changes to the 2nd make perfect sense, thanks.

**Comment by AramZS** [comment]
Yup! Great!

**Comment by AramZS** [comment]
Changes made.

**Comment by lmarkou1** [comment]
For "#25: Can measure avails" - I would deprioritize the importance of this. Some forecasting would be great but I don't think anyone has an accurate foothold on measuring or forecasting available ad inventory today. Very much an educated guessing game.

**Comment by csharrison** [comment]
@lmarkou1 I think this is a standin for measuring incrementality. E.g. if browser vendors were _opposed_ to measuring avails, it would be impossible to run incrementality / lift studies.

**Comment by eriktaubeneck** [comment]
It would be useful to be more specific about the definition of "avails". I understood it in the same way as @csharrison, i.e. there is some way to measure that a person had the opportunity to see an ad, and then took an action.

**Comment by AramZS** [comment]
@eriktaubeneck @csharrison I think maybe you may be working with a different definition than is standard among ad tech and adops professionals. 

Would "impressions without clicks" be a more precise stand-in for what you are trying to talk about  in the document?

**Comment by eriktaubeneck** [comment]
I just looked it up, and you're right @AramZS. I think we probably need a new item for what @csharrison and I are referencing, something like "ad opportunity". I don't think "impressions without clicks" works (isn't that just a view?), as an opportunity would be something like "intent to treat" in a lift test, where the user may or may not actually receive an impression, depending on their assignment to test or control group.

**Comment by csharrison** [comment]
Yes I've been using the term "avail" to mean an ad opportunity. I don't mind changing the terms if that's clearer.

**Comment by AramZS** [comment]
Ok, I think I understand this a little better, yeah, avails is not the word we want to use here, but I also think we're discussing a property that most ad tech folks outside of platforms don't use that frequently. Capacity to win a bid and choice to not take that win isn't something I've commonly heard done because existing systems cannot reliably report on that. Generally they win the bid, show a dummy creative to the control user, or something like that where they retain the capacity to show the user an ad and can measure a view normally. But I understand what you are saying here and we should discuss.

@eriktaubeneck @csharrison How about "released ad opportunities, where you choose not to act on an eligible user in situations where you have otherwise secured the ability to do so"?

**Comment by csharrison** [comment]
> @eriktaubeneck @csharrison How about "released ad opportunities, where you choose not to act on an eligible user in situations where you have otherwise secured the ability to do so"?

I do think there are some situations where rather than a dummy creative being shown, a second place ad (or similar) is placed. In that sense the winning ad might not have "fully secured" the ability to render, but it is allowed measurement. I think we should let the definition be flexible enough to support that use-case.

**Comment by michaelkleber** [comment]
Any chance the terminology "ghost impression" is useful here?  I believe that's what https://journals.sagepub.com/doi/10.1509/jmr.15.0297 (by @garjoh) called it when they advocated for this measurement approach.

**Comment by AramZS** [comment]
I'm not sure that "ghost impression" has caught on to the mainstream (noting the availability of the paper here: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2620078 for the interested) and is a specific methodology. Unless everyone agrees that specific methodology is what is intended by `avails` in the document I think maybe it sounds like "ad opportunities where the user was eligible to be shown an ad but, due to a choice made by an advertiser-authorized system in order to measure that user as a control group for testing, have withdrawn their ad from being shown"

Sorry, I know this is wordy, but trying to get the general definition in here in a way that will be clear to all participants. If the document editors believe that 'ghost impression' and the process described in @garjoh's paper is the intended specific process we want to explore, I'm find just saying 'ghost impression' and linking to the paper.

**Comment by lmarkou1** [comment]
I've used "win rate" to designate the % of available impressions that I've actually won (purchased) as a buyer. But total impression opportunities that are available for an advertiser to bid on (based on targeting criteria) are referred to as avails.

**Comment by eriktaubeneck** [comment]
@AramZS How about
> Can measure opportunities (an opportunity is when a user is eligible to be shown an ad but, due to a choice made by an advertiser-authorized system in order to measure that user as in a test or control group for testing, may have withdrawn or replaced the ad from being shown.)"

I think it's fine to be wordy, but better to use the term "opportunity" and then define it in the parens. Also, for clarity, opportunity is typically a super set of impressions, so the ad may or may not end up being shown/withdrawn/replaced.

**Comment by garjoh** [comment]
Ghost ads+ is broadly used as a term and in practice. We know of about 30
firms that have used these methodologies including Google, Criteo, Pandora,
Xandr, Roku, Yahoo!, Nielsen Catalina Solutions, and many smaller firms. My
site lists a couple dozen mostly industry blog posts that explain the
concept: https://www.garjoh.com/research/.

When you run a holdout experiment where the control group does not see the
focal ad campaign, you have the challenge of identifying counterfactual
exposed users: i.e., users in the control group who would have been exposed
to the focal ad campaign if they had been assigned to the treatment group.
We propose three related methodologies:

   - Ghost ads: Tag ads/impressions in the control group where the user
   would have seen the focal ad.
   - Ghost bids: Tag ad/impressions in the control group where the focal
   advertiser would have bid on. This--together with logging bids in the
   treatment--identifies a superset of users that an advertiser wants to bid
   on.
   - Predicted ghost ads: Tag ads/impressions in the treatment and control
   group where you intended to show the ad. This is useful for situations
   where you don't fully control the ad allocation process e.g. due to
   publisher's advertiser exclusions or ad time outs. This identifies the
   superset of users that the advertiser intended to bid on. In principle you
   could do related approaches in this vein, but this is how we apply it in
   our paper.

Based on the above, I think you are describing "predicted ghost ads." If I
follow correctly, I humbly suggest calling it that because it has a
well-defined meaning and the general concept is familiar to people who run
ad experiments.

Thanks @michaelkleber!

**Comment by bmayd** [comment]
> Based on the above, I think you are describing "predicted ghost ads." If I follow correctly, I humbly suggest calling it that because it has a well-defined meaning and the general concept is familiar to people who run ad experiments.

I support the use of this language both given its precedent and that it is distinctly different from other placement related terms.

**Comment by AramZS** [comment]
I think that generally the hope in having the event in NYC is that we might include participants who are less aware of terms like ghost ads but can speak to the stakes of what we want to accomplish. In that spirit I've used the term as suggested but added the explanation--lightly modified for clarity for the new presentation--supplied by @eriktaubeneck

**Comment by AramZS** [comment]
Since we have not had responses, we'll spend about 20m towards the beginning of day 1 to review this list and collect responses. Would people find some sort of digital form appropriate for this? If there are no objections I think I'll look at setting one up that will be opened just for the duration of the specific session. In order to assure that we're getting the correct responses from participants you would have to submit your email, which I will not publish.

**Comment by AramZS** [comment]
NOTE: If, for whatever reason, you could not fill this form during the period in the meeting, let me know via email or Slack, I will coordinate with you a time to re-open the poll

**Comment by benjaminsavage** [comment]
I do not understand this question: "User data is limited by a privacy budget, with the amount of properties about a user further limited if the TLD delegates to a measurement provider outside of the TLD"

What do you mean by "amount of properties about a user"? What kind of "properties" are we talking about?

**Comment by AramZS** [comment]
Strong concerns and interest in table here - https://chart-builder-patcg.glitch.me/ 
Graphs of results and link to CSV here - https://docs.google.com/document/d/1bydwuN0_K2anOZV41xNJn1Kt0vt9WPOkf56ESnmQ5_A/edit?usp=sharing

**Comment by AramZS** [comment]
Heads up that we will be continuing this process in the upcoming meeting.

**Comment by AramZS** [comment]
We will continue to review these in the upcoming meeting.

**Comment by AramZS** [comment]
Let me know if we want to add a continuation of this to day 2 of 12/5
