### ISSUE TITLE
Agenda Request -  Topics API 

### ISSUE THREAD

**Issue by jkarlin** [patcg/meetings#92]
## Agenda+: Topics updates and community feedback
I've been requested to find some time at the NYC F2F to discuss the Topics API and do a bit of a q/a given recent feedback from browsers and TAG. I'd also like to discuss the general use case and understand if the group is up for tackling it. 

## Time
30 minutes is probably sufficient.

### Links

Topics explainer: https://github.com/patcg-individual-drafts/topics

**Comment by fabiopereira7815-spec** [comment]
> ## Agenda+: Atualizações de tópicos e feedback da comunidade
> Fui solicitado a reservar um tempo no encontro presencial em Nova York para discutir a API de Tópicos e fazer algumas perguntas e respostas, considerando o feedback recente de navegadores e do TAG. Gostaria também de discutir o caso de uso geral e entender se o grupo está disposto a trabalhar nisso.
> 
> ## Tempo
> 30 minutos provavelmente são suficientes.
> 
> ### Links
> Explicação dos tópicos: https://github.com/patcg-individual-drafts/topics
