### ISSUE TITLE
Agenda Request - Use cases and principles for Attribution/Measurement proposals 

### ISSUE THREAD

**Issue by tprieur** [patcg/meetings#96]
### Agenda+: Use cases and principles for Attribution/Measurement proposals
Collecting feedback from our clients and the buy side in general, Criteo published a list of use cases we need to address when building new measurement APIs. We'd like to review the document and collect your feedback.

### Time
20 minutes is probably sufficient.

### Links
https://github.com/patcg/proposals/issues/14

**Comment by AramZS** [comment]
Hi @tprieur ! 

I think that while we have given Topics a space to incubate we have generally agreed that we're trying to spend a minimal amount of time on it until it has advanced out of the incubation space. I'm not adverse to spending time on it, but just to be clear: Is your proposed session about metrics specific to Topics API or is it about lessons learned from experimenting with Topics API that should influence our requirements around Metrics? This will also help with deciding what day to put it on.

**Comment by tprieur** [comment]
Hi @AramZS  ! 
This is nothing specific with Topics, more a proposition to evaluate any Measurement proposals. It is somehow related to https://github.com/patcg/meetings/issues/91
